# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 00:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20180816_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 0, 40, 6, 558509)),
        ),
    ]
