# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-09 00:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20180909_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 7, 1, 178059)),
        ),
    ]
