# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-04-13 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20180909_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='regionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Region'),
        ),
    ]
