# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('smart_find', models.BooleanField(default=True)),
                ('image', models.CharField(max_length=1000, null=True)),
                ('location', models.CharField(max_length=1000, null=True)),
                ('cv', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 2, 23, 996397))),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 2, 23, 998337)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 2, 23, 997399)),
        ),
    ]
