# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 23:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20180816_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 6, 4, 786617)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 6, 4, 786060)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 6, 4, 785389)),
        ),
    ]
