# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180816_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 344871)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 344340)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 343657)),
        ),
    ]
