# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-09 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20180909_0006'),
        ('account', '0005_auto_20180818_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industryID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Industry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 721956)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 721426)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 720853)),
        ),
    ]
