# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-09 02:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180909_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='brojuposlenih',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='brojtelefona',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 154676)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 154034)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 153315)),
        ),
    ]
