# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-17 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180916_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='editovanProfil',
            field=models.BooleanField(default=False),
        ),
    ]
