# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-17 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_employee_strucnasprema'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='obrazovanje',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
