# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-17 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_employee_obrazovanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='iskustvo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='radnoMjesto',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
