# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-17 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20180909_1619'),
        ('account', '0018_remove_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.City'),
        ),
    ]
