# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-22 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20181017_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='editovanProfil',
            field=models.BooleanField(default=False),
        ),
    ]
