# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-23 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_userprofile_editovanprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='web',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
