# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20181025_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
