# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-20 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20181025_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='opis',
            field=models.TextField(null=True),
        ),
    ]
