XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
	XXXXXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
	XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XX XXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
				XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXX
				XX XXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXX
					XXXXX
						XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXXX
						XXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXX XXXX XXXXXXXXXX XXX XXX
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXX
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXX XXXXXX
				XXXXX
					XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
					XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXX XXXXXX
				XXXXXX
				XXXXX
					XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
					XXXXXXXX
						XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
			    		XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
					XXXXXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXX XXXXXX
					XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXX
						XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
			    		XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
					XXXXXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXX XXXXXX
					XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
					XXXXXXXX
						XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
			    		XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
			    		XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
			    		XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
			    		XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
					XXXXXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX
					XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX
					XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXX XXXXXXXX
						XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
				XXXXXX
				XXXX  XXXXXXXXXXXXXXXXXX XXXXXXX
					XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
					XXXX XXXXXXXXXX XXXXXXXXX XXX
					XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
      				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXX XXXXXXXX XXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
					XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX
						XXXXX
							XXXXXX XXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXX
						    	XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX
						    		XXXXXXX
							XXXXXXXX
						XXXXXX
						XXXXX
							XX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX X XXXXXXX
						XXXXXX
					XXXXXX
				XXXXXX
				XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
			XXXXXXX
		XXXXXX
	XXXXXX XXXX XXXXXXXXX XXX XXX
	XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX
				XXXXXXXXXXX XX XXXXX  XXX XXXX X XXX XXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXX XXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXX XXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX XXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XX XXXX XXX XXXXX XXXXXXXX XXXXXXXX XXX XX XXX XXXX XXXXX XXXXXXXX XX XXX XXXXXXXXX XXXXXXXXXXX XXX XXXXX XXXXXX XXX XX XXX XXXXXX XXXXXXX XX XXXXXX XXXXXXX XXXX XX XXXXX XXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXX XXX XXX XXXXXX XXXXXX XXXXXXX XXX XX XXXXX XXXXXXX XXXXXXXXXX XXXX XXX XX XXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXX XXXXXXX
			XXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XX XXXX XXXXXXXX XXXXXXXXXX XX XXXX XXX XXXXX XXXXXX XXX XX XXXXX XXXXXXX XXXXXXXXXX XXXX XXX XXXXXX XXXXXXXXX XXXXXXXXX XXX XXX XXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXX XXX XXX XX XXXXX XXXXXXX XXXX XX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXX XX XXXX XX XXXXXXX XXXXXXXX XXXX XX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXX XXX XXXXXX XXXXXX XXXXXXXXXX XXX XXX XXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XX XXX XXXXXX XXXXXXX XXXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXX
					XXXXXXXXXXXXXXX XXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXX XXX
					XXXXXXXXXXXXXX XXXXXXXXXXXX
					XXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
	XXXXXX XXXX XXXXXXXXX XXX XXX
	XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXX XXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		  XXXXXXXXXXXXXX
		XXX
	XXXXXXXXX
XXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXX XXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXX X
    XXXXXXXX X
      XXXXXXXX XXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
      XX XXXXX XXXXXXXXX XX X XXXXX XXXXXXXX XX
    X
  XX
  XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXX
  XXXXXX XXXXXX
XXX
XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXX X XXXXXXXXXX X
  XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXX
XX

XXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
	XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
	XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXX
XXX

XXXXXXXXX
XXXXXXX
