# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 20:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 20, 39, 30, 24865))),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 20, 39, 30, 28396))),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 20, 39, 30, 23085))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100, null=True)),
                ('type', models.IntegerField(db_index=True)),
                ('b2b_type', models.IntegerField(null=True)),
                ('experience', models.IntegerField(default=1)),
                ('contact_email', models.CharField(max_length=100, null=True)),
                ('contact_phone', models.CharField(max_length=50, null=True)),
                ('attachment', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 20, 39, 30, 23980))),
                ('industryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Industry')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 20, 39, 30, 27211))),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 20, 39, 30, 26522))),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 20, 39, 30, 25383))),
            ],
        ),
        migrations.CreateModel(
            name='UserCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 20, 39, 30, 27813))),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkersPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 20, 39, 30, 25878))),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='posttags',
            name='tagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Tag'),
        ),
    ]
