# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180816_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 348250)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 352318)),
        ),
        migrations.AlterField(
            model_name='industry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 346653)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 347438)),
        ),
        migrations.AlterField(
            model_name='postcategories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 351062)),
        ),
        migrations.AlterField(
            model_name='posttags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 350304)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 348681)),
        ),
        migrations.AlterField(
            model_name='usercategories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 351689)),
        ),
        migrations.AlterField(
            model_name='workersposts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 7, 50, 349366)),
        ),
    ]
