# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 00:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180816_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 0, 40, 6, 560827)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 0, 40, 6, 564129)),
        ),
        migrations.AlterField(
            model_name='industry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 0, 40, 6, 559294)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 0, 40, 6, 560068)),
        ),
        migrations.AlterField(
            model_name='postcategories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 0, 40, 6, 562986)),
        ),
        migrations.AlterField(
            model_name='posttags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 0, 40, 6, 562423)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 0, 40, 6, 561254)),
        ),
        migrations.AlterField(
            model_name='usercategories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 0, 40, 6, 563577)),
        ),
        migrations.AlterField(
            model_name='workersposts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 0, 40, 6, 561779)),
        ),
    ]
