# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-09 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180818_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 717136)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 720299)),
        ),
        migrations.AlterField(
            model_name='industry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 715528)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 716403)),
        ),
        migrations.AlterField(
            model_name='postcategories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 719164)),
        ),
        migrations.AlterField(
            model_name='posttags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 718552)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 717554)),
        ),
        migrations.AlterField(
            model_name='usercategories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 719732)),
        ),
        migrations.AlterField(
            model_name='workersposts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 0, 6, 2, 717984)),
        ),
    ]
