# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-09 02:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20180909_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 148904)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 152655)),
        ),
        migrations.AlterField(
            model_name='industry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 147029)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 148023)),
        ),
        migrations.AlterField(
            model_name='postcategories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 151382)),
        ),
        migrations.AlterField(
            model_name='posttags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 150639)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 149417)),
        ),
        migrations.AlterField(
            model_name='usercategories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 152024)),
        ),
        migrations.AlterField(
            model_name='workersposts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 2, 58, 7, 149958)),
        ),
    ]
