# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20180909_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
