# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20180916_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
