# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
