# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-01 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20180930_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
