# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20181001_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brojIzvrsitelja',
            field=models.IntegerField(default=1),
        ),
    ]
