# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-17 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_post_brojizvrsitelja'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slika',
            field=models.IntegerField(default=0),
        ),
    ]
