# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-31 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0021_category_slika'),
    ]

    operations = [
        migrations.CreateModel(
            name='izlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('location', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('attachment', models.FileField(null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('soft_delete', models.BooleanField(default=False)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
