XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    BBBB BBBBBB
	XXXXXXXXXXXXXX X XXXXXXX XXXX XXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBXX XXXX XXXXXXX XX XXXXXXX XXXXXXXXXXXX XXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX XXXX XXXXXXX XX XXXXXXX XXXXXXXXXXXX XXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX XXXX XXXXXXX XX XXXXXXX XXXXXXXXXXXX XXX

    XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX

  XXXXXX XXXXXXXXXXXXXXXX
  XXXXXXXX
  	XXXXXXXXXXX XXXXXX
  X
		XXXXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXXXX
			XXXX XXXXX
			XXXXXX XXXXX
			XXXXX XXXXXX
			XXXXXXXX XXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X

		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX X
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
				XXXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXX XXXXXXXXXXX
			X
		X
	XXXXXXXX
	XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXX X
			XXXXXXXX XXXXX
			XXXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXX XX
		X
		XXXXXXXXXXXXXXXX XXXX
			XXXXXXX XXXXXXXX
			XXXXXXX XXXXX
			XXXXXX XXXXX
			XXXXXXXXXXXXXX XXXX
			XXXXXXXXXXXXXXXXX XXXXX
			XXXXXXXXXX XXXXX
			XXXXXX XXXXXXXX
			XXXXXXXXXXXX XXXXXXX XXXXXXXXX
			XXXXXXXX XXXXX
				XXXXXXXXXXXXXXXX XXXXXXX
				XXXXXXXXXXXX XXXXXXX
				XXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXX X XXXX
			XXXXXXXXXXXXX XXXX
			XXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XXXX XXXXXX
		X
		XXXXXXXXXXXXXXXX X XXXXXXXXXX
			XXXXXXXXXXXXXXXXX XXXXXXXX
				XXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XXXX XXXXXX
				XXXXXX XXXXXXXX
		X
		XXXXXXXXXX
				XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
				XXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XX XXXX XXXXXXXXXXX
				XXXXXX XXXX XXXXXXXXXXX
		X
    XXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    BBBB BBBBBBBBB BBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBB
    BBBBBBB

    XXXXXX XXXXXXXXXXXXXXXX
    	XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    	X
    	XXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXX
    		XXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXX
			X
		X
    XXXXXXXX

XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
			XXXXX
				XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXXXXXXXXXXXXXX
				XXXXXXX XXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXXXXXXXXX XXXXXXXXXX
				XXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXX XXXXX XXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XX XXXX XXX XXXXX XXXXXXXX XXXXXXXX XXX XX XXX XXXX XXXXX XXXXXXXX XX XXX XXXXXXXXX XXXXXXXXXXX XXX XXXXX XXXXXX XXX XX XXX XXXXXX XXXXXXX XX XXXXXX XXXXXXX XXXX XX XXXXX XXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXX XXX XXX XXXXXX XXXXXX XXXXXXX XXX XX XXXXX XXXXXXX XXXXXXXXXX XXXX XXX XX XXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXX XXXXXXX
			XXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XX XXXX XXXXXXXX XXXXXXXXXX XX XXXX XXX XXXXX XXXXXX XXX XX XXXXX XXXXXXX XXXXXXXXXX XXXX XXX XXXXXX XXXXXXXXX XXXXXXXXX XXX XXX XXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXX XXX XXX XX XXXXX XXXXXXX XXXX XX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXX XX XXXX XX XXXXXXX XXXXXXXX XXXX XX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXX XXX XXXXXX XXXXXX XXXXXXXXXX XXX XXX XXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XX XXX XXXXXX XXXXXXX XXXXXXXXXXXXX
		XXXXXX
			XXXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
			    XXXXXXXX XXXXX
			    XXXXXXXXXXXXXXX XXXXXXX
			    XXXXXXXXXXXX XXXXXXXXXXX
			X
			XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
				XXXXXXXXXXXX X XXXXXXXXXXX
			X
			XXXXXX
				XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
				XXXXXXXXXXX XXXXX
				XXXXXX XXXXX
				XXXXXXXXXXXXX XXXXXX
				XXXXXXX XXXXX
			X
			XXXXX XXXX
				XXXXXXXXXX XXXXXX
				XXXXXXXXXX XXXXXX
			X
			XXXXXXXXXXXXX XX
				XXXXXXXXXXXXXXXX XXXXX
				XXXXXX XXXXXXXX
			X
			XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXXX X
			    XXXXXXXXXXXXXXXXXXXXXXX XXXX
			    XXXXXXXXXXXXXXXXXXXXXXXX XXXX
			X
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
			    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
			    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
			X
			XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXX XXXXX
			    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
			X
			XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
			    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
			X
		XXXXXXXX

		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX

			XXXXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXX XXX XXXX X XXXXXXX XXXX XXXX XXXXX
    XXXXXXXX XXXX XXXX XXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX XXXXXXX
    XXXXXXX XXXXXXXX
X
			XXXXXXXX


        BB BBBBBBBBBBBB BB B

            XXXXXXX XXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXX

        BBBBB

            BBB B BB BBBBBB
			XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXX
				XXXX XXXXXXXXXXXXXXXXXXX
					XXXXX
						XXXXX
							XXXXX XXXXXX XXXX XXX X XXXXXXX XXXXXXXXX XXX
                            XXXXX
								XXXXXX

                                    BB BBBB
                                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						    		XXXXXXX XX
                                    BBBB
                                        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XX XX XXXXXX
						    		XXXX XX
                                            BBBBB
							XXXXXXXX
								XXXXXXX
								XXXXXX
									XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXX XX XXXXX XXX
									BB BBBBBBBBBBBBBB XXX BBBBBX XXXXX X XXXXXXXXXXX XXXX XXXXX XXXXX X XXXXXXXXXXX XXX
								XXXXXXX
							XXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXXXXX XXXXXBB BBBBBBBBBBBBXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXXXXXX
					XXXXXX
				XXXXXX
			XXXX
            BBBBBB



            XXXXX
	                	XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                            BBB B BB BBB
                                BB B BB BBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                BBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            BBBBB
                            BBBBBB
	                	XXXXXX
                	XXXXXX
			XXXXXX XXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXX
					XXXXX
						XXXXX
							XXXXXXXXX XXXXXXXXXXXXXXX XXXX XXX X XXXXXXX XXXXXXXXX
							XXXXX
								XXXXXX
									XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
						    		XXXX XX
							XXXXXXXX
								XXXXXXX
								XXXXXX
									XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXX XX XXXXX
									XXXXXX XXXXX X XXXXXXXXXXX XXXX XXXXX XXXXX X XXXXXXXXXXX
								XXXXXXX
							XXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXXX
					XXXXXX
				XXXXXX
			XXXXXXX

        XXXXXX

	XXXXXX

   XXXXX


    BBBB BBBBBBBBB
			BBBBBBB BBBBBBBBBBBBB
            BBBBBBB

XXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX XXXX XXXXXXX XX XXXXXXX XXXXXXXXXXXX XXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XX
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX
XXXXXXX