XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    BBBB BBBBBB
	XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBXX
	XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX

        XX
            XXXXXXXXXXXXXXXX XXXXX
        X

    XXXXXXXX

XXXXXXX
XXXXXX
XXXXXX XXXXXXXXXXXXXXXX
	XX X XXXXXXXXXXX XXXX X
	XXXXXXXXXX X
		XXXXXXXX XXXX
		XXXXXX XXXXXXXX
  		XXXXXXXX XXXXXXXXXXXXX
  		XXXXXX XXXX
  		XXXXXXXXXXXX XXXX
  	X
	XXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXX XXXXXX
		XXXXXXX XXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXX XXXXX
		XXXXXX XXXXXX
		XXXXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXX XXX XXX XXXXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXX
		XXXXXXXXXXXXXXXXX XXXXXX
	X
	XXXXX XXX
    	XXXXXXXXXX XXXXX
    	XXXXXX XXXXXXXX
    	XXXXXXXXXXXX XXXXXXX XXXXXXXXX
    	XXXXXXXXXXXX XXXXX
	X
	XXXXX XXXXXXXXXXXXXXXX
    	XXXXXXXXXXXXXX XXXXX
    	XXXXXXXXXXXX XXXXX
	X
	XXXXX XXXXXXXXXXXXXXXX
    	XXXXXXXXXXXXXX XXXXX
    	XXXXXXXXXXXX XXXXX
    X
	XXXXX XX X XXXX X
    	XXXXXXXXXXXX XXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXX
  		XXXXXXX XXXXXX
  		XXXXXXXXXXXXXX XXXXX
  		XXXXXXXXXXXXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXX XXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXXX
		XXXXXXX XX
		XXXXXXXX XX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXX
		XXXXXXXXXXX XXXXX
		XXXXXXXX XX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX
		XXXXXX XXXXX
  		XXXXXXX XXXXX
  		XXXXXXXXXXXXXX XXXX
  		XXXXXXXXXXXXXXXXX XXXXXXXX
  		XXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXX XXX XXXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXXX XXXXX
  		XXXXXXXXXX XXXXX
  		XXXXXXXXXXXX XXXXXXX XXXXXX
  		XXXXXXXX XXXXX
  		XXXXXXXXXXXXXXXX XXXXXXX
  		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXX
		XXXXXXXXXXXXXX XXXXX
  		XX XXXXXXXXXXXXXXXXX XXXXXXXX XX
  		XXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXX XXXXXXX
		XXXXXXX XXXXXX
		XXXXXX XXXXXXX
		XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
	X
	XX
	XXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
	X
	XX
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXX XXXXX
  		XXXXXXXXXXXX XXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXXX XX
  		XXXXXXXXXXXX XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXX
		XXXXXXXXXXXXX XXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXX XXXXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXX
		XXXXXXXX XXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXX
		XXXXXXX XXXXX
		XXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXX XXX XXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXX
 	 	XXXXXXX XXXXX
  		XXXXXXXXXXXXXX XXXX
  		XXXXXXX XXXXX XXX XXXXXXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXXX XXXXXXX XXXXXX
  		XXXXXXXXXXXX XXXXX
  		XXXXXXXXXX XXXXXXX
  		XXXXXXXX XXXXX
  		XXXXXXXXXXXXXXXX XXXXXXX
  		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXX XXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXX XXXXX
		XXXX XXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXXX XXXXX
		XXXX XXXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXX
		XXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXX XX
	X
	XXXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXX XXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXX XXX
  		XXXXXXXXXXXX XXXXXXX XXXXXXXX
  		XXXXXXXXXX XXXXX
  		XXXXXXXXXXXX XXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXX XX
  		XXXXXXXXXXXX XXXXX
  		XXXXXXXXXXXXXX XXXXX
	X
	XXXXXX
		XXXXXX XXXXXXX
		XXXXXXX X XXXXX
	X
	XXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXX
  		XXXXXXX XXXXX
  		XXXXXXXXXXXXXX XXXX
  		XXXXXXXXXXXXXXXXX XXXXXXXX
  		XXXXXXXXXXX XXX XXX XXXX X XXXXXXX XXXX XXXX XXXXXX
  		XXXXXXXX XXXXX
  		XXXXXXXXXXXXXXXX XXXXXXX
  		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXXX XXX XXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
	X
	XXXXXXXXX X XXXXXXXXXXXXXXXXX
		 XXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XXXX XXXXXX
		 XXXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXX X XXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXX
		XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
	X
	XXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXX XXXXX
  		XXXXXXXXXXXX XXXX
  		XXXXXXXXXXXX XXXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXXX XXXXXXX XXXXXXXX
  		XXXXXXX XXXXXXXX
	X
	XXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
		XXXXXXXXXXX XXX XXX XXX X XXXXXXX XXXXXXXXXXX
	X

	XXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXX XXXXXX
		XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
	X

	XXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXX XXXXXXXXXXX
	X

	XX
	XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX 
		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
		XXXXXXXXXXX XXX XXX XXXX X XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX 
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX 
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX 
		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
		XXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXXX XXX XXXXX XXXXXXXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX 
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX 
		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
		XXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
		XXXXXXX XXXXXXXX
	X
	XX

	XXXXXXXXXXX
		XXXXXXX X XXXXX
		XXXXXXXXXXX XXXXX
		XXXXXXXXXXX XXX XXXX XXXXX X XXXXXXXX XXX XXX XXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXXXXX XXXXXXXXXXX
	X
	XXXXXXX
		XXXXXXX XXXXX
		XXXXXX XXXXX
	X
	XXXXXXXXXXXXXXX
		XXXXXX XXXXXXX
		XXXXXXX X XXXXX
		XXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXXXX
	X
	XXXXXXXXXX XXXXXXXXXXX
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXX XXXXXXXXXXX
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXX XXXXXXXXXXX
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXX XXXX
	XXXXXXXXXXXXXXXXXXX XXXX
	XXXXXXXXXXXXXXXXXX XXXX
	X
	XXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
  		XXXXXXXXXXX XXX XXXX XXXX X XXXXXXXXX XXXX XX XXXXX
  		XXXXXXXXXXXXX XXXXX
  		XXXXXXXXXXXX XXXXXX
  		XXXXXXXXXXXXXX XXXX
  		XXXXXXXXXXXXXX XXXXX
	X
	XXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXX XXXXXX
		XXXXXXXXXXX XXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXXXXXX
		XXXXXXXXXXXX XXXXX
  		XXXXXXXXXXXXXXX XXXXX
	X
	XXXXXXX XXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXX XXXXXXX
  		XXXXXXXXXXXX XXXX
  		XXXXXXXXXXXX XXXXXXX XXXXXXXX
  		XXXXXXXXXXXX XXXX
	X
	XXXXXXXXXXXXXXXXXX
	    XXXXXX XXXXXX
	    XXXXXXX XXXXX
	    XXXXXXXXXXXXXX XXXX
	    XXXXXXXXXXXXXXXXX XXXXXXXX
	    XXXXXXXXXXXX XXXXXXX XXXXXXX
	    XXXXXXXXXX XXXXX
	    XXXXXX XXXXXXXX
	    XXXXXXX XX
	    XXXXXXXX XXXXX
	    XXXXXXXXXXXXXXXX XXXXXXX
	    XXXXXXXXXXXX XXXXXXX
	    XXXXXXX X XXXXX
	    XXXXXXXXXXX XXXXXX
	    XXXXXXXXXXXXXX XXXXX
	X

    	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXX XXX
			XXXXXXXXXX XXXXX
		X
		XXXXX XXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXX
		    XXXXXXXXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX
			XXXXXXXXXX XXXXX
			XXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXX XXXXX
			XXXXXXX XXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXX XXXXX
			XXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXX XXX
			XXXXXXXXXX XXXXX
			XXXXXXXXXXXX XXXXXX
		X
		XXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXXX
		X
		XXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXXX
		X
		XXXXXX
			XXXXXX XXXXX
		X
		XXXXXXXX
			XXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXX XXXXX XXXXXXXXXXX
		X
		XXXXXXX XXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXX
			XXXXXXXXXXXX XX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXX
			XXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXX XXXXX
			XXXXXXXX XXXXX
			XXXXXXXXXXXXXXX XXXX
			XXXXXX XXXXX
			XXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXX XXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXX XXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXX
		XXXXX XXX
			XXXXXXXXXXXX XXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXX
			XXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXX XXXXXXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XX
		X
		XXXXXXXXXXXXXXX
			XXXXXX XXXXXX
			XXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XX
			XXXXXXXXXXX XXXXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXX XXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    		XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXXX XXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXX
			XXXXXXX XXXXX
			XXXXXXXXXXX XXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXX XXX
			XXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXX XX
			XXXXXXXXXX XXXXXXXXXXX
			XXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXXXXXX XXXX
			XXXXXXXX XXXXXX
		X
	X
    XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
    X
XXXXXXXX
   
      XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXXXX
			XXXX XXXXX
			XXXXXX XXXXX
			XXXXX XXXXXX
			XXXXXXXX XXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
		
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX X
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
				XXXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXX XXXXXXXXXXX
			X
		X
	XXXXXXXX
	       XXXXXX XXXXXXXXXXXXXXXX
                	XXXXXXXXXXXXXXXX X
    					XXXXXXXX XXXXX
    					XXXXXXXXXXXXXXXX XXXXXXX
    				X
    				XXXXXXXXXXXXXXXX XXXX
						XXXXXXX XXXXXXXX
						XXXXXXX XXXXX
						XXXXXX XXXXX
						XXXXXXXXXXXXXX XXXX
						XXXXXXXXXXXXXXXXX XXXXX
						XXXXXXXXXX XXXXX
						XXXXXX XXXXXXXX
						XXXXXXXXXXXX XXXXXXX XXXXXXXXX
						XXXXXXXX XXXXX
			  			XXXXXXXXXXXXXXXX XXXXXXX
			  			XXXXXXXXXXXX XXXXXXX
			  			XXXXXXXXXXX XXXXX
					X
					XXXXXXXXXXXXXXXX X XXXX
						XXXXXXXXXXXXX XXXX
						XXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XXXX XXXXXX
					X
					XXXXXXXXXXXXXXXX X XXXXXXXXXX
						XXXXXXXXXXXXXXXXX XXXXXXXX
			  			XXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XXXX XXXXXX
			  			XXXXXX XXXXXXXX
					X
					XXXXXXXXXX
			  			XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
			  			XXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XX XXXX XXXXXXXXXXX
			  			XXXXXX XXXX XXXXXXXXXXX
					X
                XXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    BBBB BBBBBBBBB BBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBB
    BBBBBBB

    XXXXXX XXXXXXXXXXXXXXXX
    	XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    	X
    	XXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXX
    		XXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXX
			X
		X
    XXXXXXXX

	XXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXX
						XXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXX XXXX XXXXXX XX XXXX XXXX XXXXXXXX XXX
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXX
						XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXX  XXXX XXXXXX XX XXXX XXXX XXXXXXXXX XXX
					XXXXXX
				XXXXXX
			XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B

                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX

                    BBBB
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   BBBBB

                BBB B BB BBBBBBBBBBB
               XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBXXX

                   XXXXX
						XXXXX
							        BB BBBBBB BB B
							
                            BBBB
                                
                            BBBBB

						XXXXXX
						XXXXX
							XXXXXXXXXXX
							XXXXXFFFFFFFF FF FFF  XXXXX BB BBB BBBBBBBBBB XXXXXXXXXXXXXXXXXX XXXXXXXBBBBB XBB BBBBBBBBBB BBBB XXXXXXXXXBBBBBXXXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXX XXXX XXXXXX XXXX XXXXXXXXXX XXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBB BBBBBBBXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBB BBBBBBBXXXXXXXXXXXXXXX
						XXXXXXXXXXX XXXX XXXX XXXXX XX XXXXXX XXXXXXX XXX
					XXXXXX
					XXXXX
						XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX
				XXXXXX
                BBBBBB
                XXXX XXXXXXXXXX XX XXXXXXX XXX
                XXXXX
                	XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX

                     BB BBBBBBBBBBBBBBBBBBBBBBBBBBB B B
                	BBB B BB BBB

                    BB B BB BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                BBBBBB
                    BBBBB
                	XXXXXX
                XXXXXX


			XXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX

                BBBB

			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
BBBBB
                BBB B BB BBBBBBBBBBBBB
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXX
						XXXXX
                            BB BBBBBB BB B
							
                            BBBB
                                
                            BBBBB
						XXXXXX
						XXXXX
							XXXXXXXXXXX
                            XXXXXFFFFFFFF FF FFFXXXXX BB BBB BBBBBBBBBB XXXXXXXXXXXXXXXXXX XXXXXXXBBBBB XBB BBBBBBBBBBBBBB XXXXXXXXXBBBBBXXXXXXXXXXXXX

						XXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXX XXXX XXXXXX XXXX XXXXXXXXXX XXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBB BBBBBBBXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBB BBBBBBBXX XXXXXXXXXXXXX
						XXXXXXXXXXX XXXX XXXXXX XXXXXX XXX
					XXXXXX
					XXXXX
						XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
					XXXXXX
				XXXXXX
                BBBBBB

                XXXX XXXXXXXXXX XX XXXXXXXX XXX
                XXXXX
                	XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B

                BBB B BB BBBB

                    BB B BB BBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                BBBBBB
                BBBBB
                	XXXXXX
                XXXXXX
			XXXXXX


		XXXXXX
       	

       	XXXXXX XXXXXXXXXXXXXXXX
       		XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXX
		XXXXXXXXXXXXXX XXXXX
  		XXXXXXXXXXXXXXXXX XXXXXXXX
  		XXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXX XXXXXXX
		XXXXXXX XXXXXX
		XXXXXX XXXXXXX
		XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXXX
		XXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXX XXXXX
  		XXXXXXXXXXXX XXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXXX XX
  		XXXXXXXXXXXX XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXX
		XXXXXXXXXXXXX XXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXX XXXXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXX
		XXXXXXXX XXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXX
		XXXXXXX XXXXX
		XXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXX XXX XXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXX
 	 	XXXXXXX XXXXX
  		XXXXXXXXXXXXXX XXXX
  		XXXXXXX XXXXX XXX XXXXXXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXXX XXXXXXX XXXXXX
  		XXXXXXXXXXXX XXXXX
  		XXXXXXXXXX XXXXXXX
  		XXXXXXXX XXXXX
  		XXXXXXXXXXXXXXXX XXXXXXX
  		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXX XXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXX XXXXX
		XXXX XXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXXX XXXXX
		XXXX XXXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX XXXXX
		XXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXX XX
	X
	XX XXXXXXXXXXXXX XXXXXX XXXXXXX
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXX XXX
			XXXXXXXXXX XXXXX
		X
		XXXXX XXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXX
		    XXXXXXXXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX
			XXXXXXXXXX XXXXX
			XXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXX XXXXX
			XXXXXXX XXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXX XXXXX
			XXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXX XXX
			XXXXXXXXXX XXXXX
			XXXXXXXXXXXX XXXXXX
		X
		XXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXXX
		X
		XXXXXX
			XXXXXX XXXXX
		X
		XXXXXXXX
			XXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXX XXXXX XXXXXXXXXXX
		X
		XXXXXXX XXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXX
			XXXXXXXXXXXX XX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXX
			XXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXX XXXXX
			XXXXXXXX XXXXX
			XXXXXXXXXXXXXXX XXXX
			XXXXXX XXXXX
			XXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXX XXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXX XXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXX
		XXXXX XXX
			XXXXXXXXXXXX XXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXXXXXXXXXXX X XXXX
			XXXXXXXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXX
			XXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXX XXXXXXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXX X XXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXXX
			XXXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XX
		X
		XXXXXXXXXXXXXXX
			XXXXXX XXXXXX
			XXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XX
			XXXXXXXXXXX XXXXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXX XXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    		XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXXX XXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXX
			XXXXXXX XXXXX
			XXXXXXXXXXX XXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXX XXX
			XXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXX XX
			XXXXXXXXXX XXXXXXXXXXX
			XXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXXXXXX XXXX
			XXXXXXXX XXXXXX
		X
	X
       	XXXXXXXX

		XXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXX XXXXXX XX XXXX XXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
				XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
				XXXX XXXXXXXXXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXXX XXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX


	BB BBBBBBBBBBBBBBBBBBB B B
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
       

                                            BBB B BB BBBBBBBBBBBBB

                                                BB BBBBBBBBBB BB B

				XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX X
					XXXXX
						XXXXX
							
						XXXXXX
						XXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXX
							XXXXX FFFFFFFF FF FFF XXXXXX XXXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX
						XXXX XXXXXXXXXXXXX XXXXXXX
					XXXXXX
					XXXXX
					XXXXXX
				XXXXXX

                                                BBBB BBBBBBBBBB BB B

				XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX X
					XXXXX
						XXXXX
							
						XXXXXX
						XXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXX
							XXXXX FFFFFFFF FF FFF XXXXXX XXXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX
						XXXX XXXXXXXXXXXXX XXXXXXX
					XXXXXX
					XXXXX
					XXXXXX
				XXXXXX
                        BBBB BBBBBBBBBB BB B
				XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX X
					XXXXX
						XXXXX
							
						XXXXXX
						XXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXX
							XXXXX FFFFFFFF FF FFF XXXXXX XXXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX
						XXXX XXXXXXXXXXXXX XXXXXXX
					XXXXXX
					XXXXX
					XXXXXX
				XXXXXX
            BBBBB
           BBBBBB
           

            XXXXXX
             BBBBB
BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
		XXXX XXXXXXXXXXXXXXX
			XXXXXXXXXXXX XX XXXXXXX XXX XXXXXXXXXXXXXX
		XXXXXX
		XXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	BBBB
    	XXXX XXXXXXXXXXXXXXX
			XXXXXXXXXXXXXX XXXX XXXXXX XX XXXX XXXXXXXXXXXXXX
		XXXXXX
		XXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        BBBBB
            XXXXXX

 

	XXXX XXXXXXXXXXXXXXXXXXXXXX
			XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
			XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXXXX
		XXXXXX


            BBBB BBBBBBBBB
			BBBBBBB BBBBBBBBBBBBB
            BBBBBBB
XXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
	
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	XXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXX

	XXXXXXXX XXXXXXXXXX
	    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
		X
    X

    XXXXXXXX XXXXXXXXXX
	    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
		X
    X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXX
	XXX

	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXX

	XXX


	XXX XXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXX
        XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXX
        XXXXXXXXXX


	XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
        XXXXXXX X X XX X X XXXXXXXXX XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXX
            XX
        X
    XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXX
        XX
    X






XXXXXXXXX

XXXXXXXX

        XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX XX XXXXXXXXX
                XXXXXXXXXXXXXXXX X XXXXXXX
            X
            XXXX X
                XXXXXXXXXXXXXXXX X XXXXXXXX
            X
            XXXXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX
                XXXXXXXXXXXXXXXXXXX X XXXXXXX
            X
            XXXX X
                XXXXXXXXXXXXXXXXXXX X XXXXXXXX
            X
            XXXXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            X
            XXXX X
                XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
            X
            XXXXXXXXX
        XXX

        XXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX
            X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            X

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXX XX XXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X

XXXXXXXXX
XXXXXXX
