XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
	XXXXXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


    BBBB BBBBBB


XXXXXX XXXXXXXXXXXXXXXX
	XXXXXXXXXXX
		XXXXXXX XXXXXXX
	X
	XXXXXXXXXXXX XXXXX X
	  XXXXXXXX XXXXX
	X
	XXXXXXXXXXXX XXXXX X XXXXXXXXXXX X
	  XXXXXXXXXXX XXXXXXXX
	  XXXXXXXXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXX XXXXX X XXXXXXXXXXX X
	  XXXXXX XXXXXXXX
	  XXXXXXXXX XXXXXXXXX
	  XXXXX XX
	  XXXXXX XX
	  XXXXXXX XXXX
	  XXXXXXXXXXX XXXXXXX
	  XXXXXXX XXXXX
	  XXXXXXXX XXXXXXXX
	  XXXXXXXXXXXX XXXXXXX XXXXXXXXX
	  XXXXXX XXXXXX
	  XXXXXXXXXXXXXXXXX XXXXXXXX
	  XXXXXXX XXXXXXXX
	  XXXXXXXX XXXX
	  XXXXXXXXXXXXXXX XXXXXXXXXX
	X
	XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
		XXXXXXXXXX X
		    XXXXXXX XXXXXXX
		X
		XXXXXXXX XXX
			XXXXXXXXXXXX XXXXXX
		X
	X
	XXXXXXXXXXXXXX
		XXXXXXXXXXXXXXX XXXXX
	X
	XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXXXXXXX X
		    XXXXXXX XXXXXXX
		X
	X
XXXXXXXX

    XXXXXX XXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXX
	XXXXXXX XXXXXX
X
	XXXXXXXXXXXXX XXXX
			XXXXXXXXXX XXXXXXX
			XXXXXXX XXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		  XXXXXXXXXXXXXXXXXXX XXXXX
		  XXXXXXX XX
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXX
				XXXXXXXX XXXXX
			X
		X
		XXXXXXXXXXX
			XXXXXXX XXXXX
			XXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXXXX
			XXXX XXXXX
			XXXXXX XXXXX
			XXXXX XXXXXX
			XXXXXXXX XXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X

		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX X
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
				XXXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXX XXXXXXXXXXX
			X
		X

		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXX X
			    XXXXXXX XXXXXX
			X
			XXXXXXXXXXXX
				XXXXXXXX XXXXX
			X
		X

		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXX XXX
				XXXXXXXXXXXXXX XXXXX
			X
		X
	XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX

	XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX


BBBB BBBBBBBBB BBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBB
    BBBBBBB


    XXXXXX XXXXXXXXXXXXXXXX
    	XXXXX
    		XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    	X
    	XXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXX
    		XXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXX
				XXXXXXXXXXX XXXXX XXXXXXXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XX
				XXXXXXXXXXX XXXXX
    			XXXXXXXXXXXX XXXXX
    			XXXXXXXXXXXXXX XXXXX
			X
		X
    XXXXXXXX


	XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XX XXXXXXBBB BBBBBBXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXX
				XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXX
				XX XXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBB
				XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXX
                BBBBB
			XXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
				XXXXXXXXXXX
				XXXXX
					XXXXX
						XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXXX
						XXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXX XXXX XXXXXXXXXX XXX XXX
	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBB X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				BBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                XXXXX
					XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
					XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXX XXXXXX
				XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
					XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXX X XXXXXXXX XXXXXXXXXXXXX XXXXXX

				XXXXXX


				XXXX XXXXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
						XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXXXX
							XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	                        XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
				    		XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
				    		XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
				    		XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
				    		XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXX
					XXXXXX
					XXXX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXXXXXX
						XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
				XXXXXX

                XXXXXX XXXXXXXXXXXX XXXXX XX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXX
				XXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

			    XXXX XXXXXXXXXXXXXXXXXXXX
	            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXX XX
	            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
	        XXXXXX
			XXXXXX

				XXXX XXXXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXX XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBB BBBBB
                        BBBBBBB BBBBBBBBBBBBBB
                        BBBBBBB
					XXXXXX
					XXXX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXX XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
					XXXX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXX XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XX XX X XXXXX X XXXXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
					XXXX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXXXX
						XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
				XXXXXX
				XXXX XXXXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
					XXXX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXXXXXX
						XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
						XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXX
					XXXXXX
				XXXXXX
				XXXX  XXXXXXXXXXXXXXXXXX XXXXXXX
					XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXX XXXXXXXXX XXX
					XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
      				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXX XXXXXXXX XXX
				XXXXXX


				XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
			XXXXXXX
		XXXXXX
	XXXXXX XXXX XXXXXXXXX XXX XXX
	XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX
               XXXX XXXXXXXXXXX XX XXXXX  XXX XXXX X XXX XXXXXXX XXX
            XXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXX XXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX XXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XX XXXX XXX XXXXX XXXXXXXX XXXXXXXX XXX XX XXX XXXX XXXXX XXXXXXXX XX XXX XXXXXXXXX XXXXXXXXXXX XXX XXXXX XXXXXX XXX XX XXX XXXXXX XXXXXXX XX XXXXXX XXXXXXX XXXX XX XXXXX XXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXX XXX XXX XXXXXX XXXXXX XXXXXXX XXX XX XXXXX XXXXXXX XXXXXXXXXX XXXX XXX XX XXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXX XXXXXXX
			XXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XX XXXX XXXXXXXX XXXXXXXXXX XX XXXX XXX XXXXX XXXXXX XXX XX XXXXX XXXXXXX XXXXXXXXXX XXXX XXX XXXXXX XXXXXXXXX XXXXXXXXX XXX XXX XXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXX XXX XXX XX XXXXX XXXXXXX XXXX XX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXX XX XXXX XX XXXXXXX XXXXXXXX XXXX XX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXX XXX XXXXXX XXXXXX XXXXXXXXXX XXX XXX XXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XX XXX XXXXXX XXXXXXX XXXXXXXXXXXXX
		XXXXXX

	XXXXXX XXXX XXXXXXXXX XXX XXX
    XXXXXX XXXXXXXXXXXXXXXX
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXXX
			X
		X
	XXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX XXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXX
			XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXX
		XXXXXX
	XXXXXX

    BBBB BBBBBBBB
BBBBBBBB
XXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX
   XX
XXX
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXX X XXXXXXXXXX X
  XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXX
XX

XXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX
		XXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXX XXXXXXXX
	X
	XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX
		XXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXX XXXXXXXX
	X
	XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXX XXXXXXXX
	X
	XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX
		XXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXX XXXXXXXX
	X
	XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
		XXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXX XXX XXXXXXXXXXXX
	X
	XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXX
	X
XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
	XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXX X
    XX XXXXXXXXXXXX XX XXXXXXXXXXXXXXX X
        XXX XXXXXX X XXX XXXXXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXX
XXX

XXXXXXXXX
XXXXXXX