XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
BBBB BBBBBB
XXXXXX
	XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX

	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


    XXXX

        XXXX

    XXX


        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX



    XXXX
    XXXXX
    XXX

	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBXX
    XXXXXXX


        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXX
            XXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXX XXXXXXXXX
            XXXXX XXXXX
            XXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXX XXX
        	XXXXXXXXXX XXXXXX
        X
        XXXXXXXXXXXXXXXXXXX XXX
        	XXXXXXXX XXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXX
        	XXXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBXXX
        X
        XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        	XXXXXXXXXXXXX XXXXX
        X
        
        XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
        	XXXXXXXX
        		XXXXXXXX XXXXX
        	X
        	XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        	XXXXXXXXXXX XXXXXX XXXXXXXXXXX
        X
        XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
		    XXXXXXXXXXXXXXXXX XXXXX
		        XXXXXXXXXXXXX XXXXX
		        XXXXXXXXXXX XXXXXXX
		X
        X



        XXXXXXXXXXXXXXXXXXX X XXXXXXX XXX XXXXXXXXXXX X
		XXXXXXXXXXXXXXXXXXX XXX
		 	XXXXXXX XXX XXXXXXXXXXX
		 	XXXXXXXXXXX XXXX XXXXXXXXXXX
		 X
		 XXXXXXXXXXXXXXXXXXXX XX X
		    XXXXXXXXXXXXXXX XXXXXXXXXX
		X

		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX XXXXXX
			X
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX XXXXXX
			X

			XXXXXXXXXX XXXXXXXXXXXXX
				XX X
				    XXXXXXXXXXXX XXXXXX
				X

				XXXX X
				    XXXXXXXXXXXX XXXXXX
				    XXXXXX XXXXXX
				X
			X


        
    XXXXXXXX

XXXXXXX
			  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
XX XXXXXXXXXXXX XXXXX
	XXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXX
  XXXXXXXX XXXXXXXXXXXXX XXXXXX XXXX
  XXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXXX
  	XXXXXXXXXXX XXXXX
  X
  XXX
  	XXXXXXXXXXXXXX XXXXX
  X
  XXX
  	XXXXXXXXX XXXXXXXXX
  X
  XXXXXXXXXX
  	XXXXXXXXX XXXXXXXXX XXXXXXX XXXXX XXXXXX XXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXX XXXXXXX
  X
  XX XXXXXXXXXXXXXXXXXXXXXXX
  	XXXX XXXX XXXXXXXXXXX
  X
  XX XXXXXXXXXXXXXXXXXXXXXXX
  	XXXX XXXX XXXXXXXXXXX
  X
  XXXXXXXXX
  	XXXXXX XXXXXXXX
  X
  XXXXXXXX XXXXXXXXXX
  	XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  	XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXX XXXXXXXXX XXXXXXXXX
    XXXX XXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXX XXX XXXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXXX
  X
  XXXXXXXXXXXXXXXX
  	XXXXXXXXXXXX XXXXX XXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
  	XXXXXXX XXXXXXXX
  X

XXXXXXXX
XXXXXXX
    XXXXXXX X
  XXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXX
  XXXXXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXX
  XXXXXXXXXX XXXXXX XX XXXXXXXXX
X

XXXXXXXXXX XXXXXX X
  XXX XXXX XXXX XXXX XXXX X
    XXXXXXXXXX XXXXXXXXXXXXXX
  X
  XXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXXX
  X
  XXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXXX
  X

XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX XXX XXXXXX XXX XXXXXXXXXXXX XXXXXXX
					XXXXXXXX
						XXXXXXXXXXXXX XXXXX XXXXXXXXXXX
						XXXXXXXXXXXXXX X XXXXXXXXXXX
						XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXX XXXXXXXXXXX
						XXXXXXXXXXXXX XXXXXX
					X
				X

				XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXX XXXXXXX
					XXXXXXXXXXXX X
					    XXXXXXXXX XXXXXXXXX
					    XXXX XXXXXX
					    XXXXXX XXXXXXX
					    XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXXXX XXXXX
					X
				X

				XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
					XXXXXXXX
						XXXXXXXXXXXXX XXXXX XXXXXXXXXXX
						XXXXXXXXXXXXXX X XXXXXXXXXXX
						XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXX XXXXXXXXXXX
						XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXX XXXXXXX
					X

					XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXX XX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
						XXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXX XXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXXXXXXX XX
					X
				X
				XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
					XXXXXXXX
						XXXXXXXXXXXXX XXXXX XXXXXXXXXXX
						XXXXXXXXXXXXXX X XXXXXXXXXXX
						XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXX XXXXXXXXXXX
						XXXXXXXXXXXXX XXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXXXXXXX XXXXX
					X
					XXXXXXXX
						XXXXXXXXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXXX XXXXX
					X
					XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX X
					    XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX X
					   XXXXXXXX XXXXX
					X
					XXXXXXXXXXXXXXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXX XXXX
					    XXXXXXXXXX XXXXXXXXXXX
					    XXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXXX XX
					X
					XXXXXXXXXXXXXXXXXXXXXXXX X
					    XXXXXXXXXXXX XXXXXXX
					X
					XXXXXXX X
					    XXXXXXXXXXXX XXXXXX
					    XXXXXXXXXXX XXXXX
					    XXXXXXXXXXXXXX XXXXX
					    XXXXXXXXXX XXXXXXXXXXX
					X
				X
				XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
					XXXXXX
						XXXXXXX XXXXXX
					X
				X
				XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
					XXXXXX
						XXXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXX XXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXXX XXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXX XXXXX
					X
					XXXXXXXXXXXXX
						XXXXXX XXXXX
						XXXXXXXXXXXXX XXXXXX
					X
					XXXXXXXX
						XXXXXXXXXXX XXXXX XXXXXXXXXXX
						XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
						XXXXXXXXXXXXX XXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXX XXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXX XXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXX XXXXXX XXXXXXXXXXX
					X
					XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
					XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XX
					XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
						XXXXXXXXXXXX XXXXX
					X
					XXXXXXXXXXXXX
						XXXXX XXXXX
						XXXXXXXXXXXXXX XXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XX
						XXXXXXXXXX XXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
						XXXXXXXXXX XXXXX
					X
					XXXXXXX X
					    XXXXXXXXXXX XXXXXXX
					    XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXX XXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXX X
					    XXXXXXXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX
						XXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX X
					    XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXX X
					    XXXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXX XXXXXXXXXXXXXX
						XXXXXXXXXXXX XXXXXX
					X
				X
XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
					XXXXXX
						XXXXXXX XXXXXX
					X
				X
				XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
					XXXXXX
						XXXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXX XXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXXX XXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXX XXXXX
					X
					XXXXXXXXXXXXX
						XXXXXX XXXXX
						XXXXXXXXXXXXX XXXXXX
					X
					XXXXXXXX
						XXXXXXXXXXX XXXXX XXXXXXXXXXX
						XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
						XXXXXXXXXXXXX XXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXX XXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXX XXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXX XXXXXX XXXXXXXXXXX
					X
					XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
					XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XX
					XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
						XXXXXXXXXXXX XXXXX
					X
					XXXXXXXXXXXXX
						XXXXX XXXXX
						XXXXXXXXXXXXXX XXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XX
						XXXXXXXXXX XXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
						XXXXXXXXXX XXXXX
					X
					XXXXXXX X
					    XXXXXXXXXXX XXXXXXX
					    XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXX XXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXX X
					    XXXXXXXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX
						XXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX X
					    XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXX X
					    XXXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXX XXXXXXXXXXXXXX
						XXXXXXXXXXXX XXXXXX
					X
				X	



			XXXXXXXX

    		XXXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXX X X
    XXXXXX XXXXXX
X
	XXXXXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
	XXXXXXXXXXXXXXXXXXXXX XXXXXXX
	XXXXXXXXXXXXXXXXXXX XXXXXXX
	XXXXXXXXXXXXXXXXXXXX XXXXXXX
	XXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
		XXXXXX XXXXXX
	X
	XXXXXXXXXXXXX XXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXX XX
		XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
	XXXXXXXXXXXXXXXXXXXXX XXXXXXX
	XXXXXXXXXXXXXXXXXXXX XXXXXXX
	XXXXXXXXXXXXXXXXXXXXX XXXXXXX
	XXXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
	X
				XXXXX
					XXXXXXXXXXX XXXXXXX
				X

				XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX XXX XXXXXX XXX XXXXXXXXXXXX XXXXXXX
					XXXXXXXX
						XXXXXXXXXXXXX XXXXX XXXXXXXXXXX
						XXXXXXXXXXXXXX X XXXXXXXXXXX
						XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXX XXXXXXXXXXX
						XXXXXXXXXXXXX XXXXXX
					X
				X

				XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXX XXXXXXX
					XXXXXXXXXXXX X
					    XXXXXXXXX XXXXXXXXX
					    XXXX XXXXXX
					    XXXXXX XXXXXXX
					    XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXXXX XXXXX
					X
				X

				XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
					XXXXXXXX
						XXXXXXXXXXXXX XXXXX XXXXXXXXXXX
						XXXXXXXXXXXXXX X XXXXXXXXXXX
						XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXX XXXXXXXXXXX
						XXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXX XXXXXXX
					X

					XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXX XX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
						XXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXX XXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXXXXXXX XX
					X
				X
				XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
					XXXXXXXX
						XXXXXXXXXXXXX XXXXX XXXXXXXXXXX
						XXXXXXXXXXXXXX X XXXXXXXXXXX
						XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXX XXXXXXXXXXX
						XXXXXXXXXXXXX XXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXXXXXXX XXXXX
					X
					XXXXXXXX
						XXXXXXXXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXXX XXXXX
					X
					XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX X
					    XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX X
					   XXXXXXXX XXXXX
					X
					XXXXXXXXXXXXXXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXX XXXX
					    XXXXXXXXXX XXXXXXXXXXX
					    XXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXXXXX XX
					X
					XXXXXXXXXXXXXXXXXXXXXXXX X
					    XXXXXXXXXXXX XXXXXXX
					X
					XXXXXXX X
					    XXXXXXXXXXXX XXXXXX
					    XXXXXXXXXXX XXXXX
					    XXXXXXXXXXXXXX XXXXX
					    XXXXXXXXXX XXXXXXXXXXX
					X
				X
				XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
					XXXXXX
						XXXXXXX XXXXXX
					X
				X
				XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
					XXXXXX
						XXXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXX XXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXXX XXXXX
					X
					XXXXXXXXXXXXX
						XXXXXXXX XXXXX
					X
					XXXXXXXXXXXXX
						XXXXXX XXXXX
						XXXXXXXXXXXXX XXXXXX
					X
					XXXXXXXX
						XXXXXXXXXXX XXXXX XXXXXXXXXXX
						XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
						XXXXXXXXXXXXX XXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXX XXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXX XXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXX XXXXXX XXXXXXXXXXX
					X
					XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
					XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XX
					XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
						XXXXXXXXXXXX XXXXX
					X
					XXXXXXXXXXXXX
						XXXXX XXXXX
						XXXXXXXXXXXXXX XXXXX
						XXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XX
						XXXXXXXXXX XXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
						XXXXXXXXXX XXXXX
					X
					XXXXXXX X
					    XXXXXXXXXXX XXXXXXX
					    XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXX XXXX
						XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXX X
					    XXXXXXXXXXX XXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX
						XXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX X
					    XXXXXXXXXX XXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXXXXXX X
					    XXXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXX XXXXXXXXXXXXXX
						XXXXXXXXXXXX XXXXXX
					X
				X

				XXXXXXXXX
					XXXXXXXX XXXXX
				X


                XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
                    XXXXXXXXXXXX X
                        XXXXXX XXXXX
                        XXXXXXXXXXXX XXXXX XXXXXXXXXXX
                        XXXXXXXXXXXXX XX
                    X
                    XXXXXXX X
                        XXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                        XXXXXXXX XXXX XXXXXXXXXXX
                    X
                    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXX XXXXXXXXXXXX
                    X
                    XXXXXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXX
                    X
                    XXXXXXXX
                        XXXXXXXXXX XXXXXXXXXXXX
                    X
                    XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX XXXXXXX
                    X
                    XXXXXXXXXXXXX
                    	XXXXXXXXXXXX XXXXXX
                    X
                    XXXXXXXXXXXXXXXX
                    	XXXXXXXX XXXXX
                    X
                    XXXXXXXXX
                    	XXXXXXXX XXXXX
                    X
                    XXXXXXXXXXXXXX X
    XXXXXXX XXXXXX
X
XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXX
X
XXXXXXXXXXXX XXX
	XXXXXXXXXXXXXX XXXXX
X



XXXXXXXXXXXXXXXXXXXXXXXXX XXX
	XXXXXXXXXX XXXXX
X
XXXXXXXXXXX XXXXXXXXXXXXXXX
	XXXXXXXXXX XXXXX
X


XXXXXXXXXXXXXXXXXXXX XX X
					XXXXXX XXXXXX
				X


                X


			XXXXXXXX

	XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXXXX
			XXXX XXXXX
			XXXXXX XXXXX
			XXXXX XXXXXX
			XXXXXXXX XXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X

		 XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
  	XXXXXXXXXXXXXXXXXXX
  		XXXXX XXXXX XXXXXXXXXXX
  	X
  X

		
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX X
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
				XXXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXX XXXXXXXXXXX
			X
		X
	XXXXXXXX
	XXXXXXXX
	  XXXXXXXXXXXXXXXXXXXXXXXX
	  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
	  XXXXXXXXXXXX XXXXXXXXXXXX
	XXXXXXXXX
XXXXXXX
XXXXXX

	XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    BBBB BBBBBBBBB BBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBB
    BBBBBBB

    XXXXXX XXXXXXXXXXXXXXXX
    	XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    	X
    	XXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXX
    		XXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXX
			X
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXXXX
		X
		XXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXX XXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
    		XXXXXXXX XXXXXX
		X

    XXXXXXXX

    BB BBB BBBB
     BB BBBB
     XXXXXX XXXXXXXXXXXXXXXX
     	XXXXXXXXXXXXXXXXXXXX
     		XXXXXXXXXXX XXXXX
     	X
     XXXXXXXX
     XXXX XXXXXXXXXXXXX
     XXXXXX
     BBBB
	XXXX XXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXX
			
			XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
			XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXX
			XXXXXXXXXX XXX XXXXXXX XXXX XXXX XXXXXXXXXXXX
			XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX
            BB BBBB
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
				XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXX XXXXXXXX XX XXXXXX XXXXXX XXXXXXX XXXXXXX
				XX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
            BBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
				XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX	
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXX XXXXXXXX XX XXXXXX XXXXXX XXXXXXX XXXXXXX
				XX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			BBBBB

		XXXXXX XXXX XXXXXXXXXXX XXX
	XXXXXX XXXX XXXX XXX
	BBBBB
	XXXX XXXXXXXXXXXXXXXXXXXXXX
		BB BBBB
		XXXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXX XXXXX
				XXXXXXXXXXXX XX
			X
			XXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXX XXXXXXX
			X

			XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
				XXXXXXXXXXXXX
					XXXXXXXXXX XXXXXXXXX
				X
			X
			XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
				XXXXXXXXXXXXX
					XXXXXXXXXX XXXXXXXXX
				X
			X

			XXXXXXXXXX
				XXXXXXXX XXXXX
			X

			XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXX XXXXXXXXXXX
				X
				XXXXXXXXXXXXX
					XXXXXXXXXX XXXXXXXXX
					XXXXXXXXXXXX XXXX
				X
				XXXXXXXXXXXXXXX
					 XXXXXXX XXXXX
				X
				XXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXX XX
					XXXXXXXXXXXX XX
				X
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXX XX
				X
				XXXXXXXXXX
					XXXXXXXX XXXXX
				X
				XXXXXXXXXX
					XXXXXXXX XXXXXX
					XXXXXXXXXXX XXXXXX
					XXXXXXXXXXXXXX XXXXXX
				X
			X

			XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
				XXXXXXXXXXXXXXXXXXXXX
					XXXXXXX X XXXX XXXXXXXXXXX
					XXXXXXXXXXX XXXXX XXXXXXXXXXX
				X
				XXXXXXXXXXXXXXX
					 XXXXXXX XXXXXX
				X
			X
			XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
				XXXXXXXXXXXXXXX
					 XXXXXXX XXXXX
				X
				XXXXXXXXXXXXXXXXXXXXX
					XXXXXXX X XXXX XXXXXXXXXXX
					XXXXXXXXXXX XXXXXX XXXXXXXXXXX
					XXXXXXXXXXXXX XXXXXX
				X
				XXXXXXXXXX
					XXXXXXXXXX XXXXXXXXXXX
					XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
				X
			X

			XXXXXXXX
				XXXXXXXXXXX XXXXXXX
			X

			XXXXX
				XXXXXXXXXXXXXXX XXXXX
			X

			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXX XXXXX
			X






		XXXXXXXX
		BBBBB
	XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
		BB BBBB
		BBBB
			XXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXX XXXXXX XX XXXXX X XXXXXXXXXX XX XXXXXXXXX
			BBBBB
			 BB BBBB
			 XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                BBB B BB BBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
					XXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXX XXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBB BB BBBBBBBBBBXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
					XXXXXX
				XXXXXX
                BBBBBB
			XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                   XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
            BBB B BB BBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
					XXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX X
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
                BBBBBB
				XXXXXX
		XXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXX
			 		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                BBB B BB BBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
					XXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXX XXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBB BB BBBBBBBBBBXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
					XXXXXX
				XXXXXX
                BBBBBB
			XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                   XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
            BBB B BB BBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
					XXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX X
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
                BBBBBB
				XXXXXX
		XXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXX
		BBBB
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX



					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
                     XX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXX XXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			BBBBB
		XXXXXX
		BB BBBB
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
                BBB B BB BBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
					XXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXX XXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBB BB BBBBBBBBBBXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
					XXXXXX
				XXXXXX
                BBBBBB
			XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                   XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            BBB B BB BBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
					XXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX X
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
                BBBBBB
				XXXXXX
		XXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXX
		BBBB
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXX
				XXXXXXX XXXXXX
			X
			XXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                BBB B BB BBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
					XXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXX XXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBB BB BBBBBBBBBBXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
					XXXXXX
				XXXXXX
                BBBBBB
			XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                   XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX
            BBB B BB BBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
					XXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX X
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
                BBBBBB
				XXXXXX
		XXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXX
		BBBBB
	XXXXXX XXXX XXXXXXXXXXXXX XXX

	BB BBBB
    BBBB
	XXXX XXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
			XXXXXXXXXXX XXXXXXXXXXX
			XX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
			XXXXXXXXXXXX XXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
		XXXXXX
		XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXX
			XX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXX
			XXXXXXXXX XXXXXXX XX XXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXX
	XXXXXX XXXX XXXXXXX XXX
	BBBBB
	BBBBB


	BB BBB BBBB
	XXXX XXXXXXXXXXXXXXX
		BB BBB BBBB
        BBB B BB BBBBBBBBB

                BB BBBBBB BB B
		XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXX XXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXBB BBBBBB BB BBBBBBBBBBXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFF FF FFF XXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXBBBBBXXXXXX
			XXXXXX
		XXXXXX
            BBBB
                BB BBB BB BBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXX XXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXBB BBBBBB BB BBBBBBBBBBXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFF FF FFF XXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXBBBBBXXXXXX
			XXXXXX
		XXXXXX
                    BBBBB
            BBBBB
        BBBBBB
        BBBBB
	XXXXXX
	BBBBB


	BB BBBB


	XXXX XXXXXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXX XXXXXX XXXXXX XX XXXXXXX XXX
		XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
			XXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBB B BB BBBBBB
			XXXX  XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXX
                              BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXX  XXBBBBB
							XXXXXX
							XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX
						XXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  XXXXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFF F FFFFXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
						XXXX XXXXX XXXXXXXX X XXXXXXX XXXXXXXXXXX XXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
				XXXXXX
			XXXXXX
            BBBBBB
            XXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXX
	               				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXX
							XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
						XXXXXX
						XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX X XXXXXXXX XXXXXXXX XXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXX
	               				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXX
							XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX
						XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX X XXXXXXXX XXXXXXXX XXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX
			XXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXX XXXXX XXXXXX XX XXXXXXXX X XXXXXXXX XXXXXX XXX
		XXXX XXXXXXXXXXXXXXXX

			 XXXX XXXX XXXXXXXX XXXXXX XXX
			XXXX XXX XX XXXXXXX XXXXX XXXX XXXXXX XXXXXXXX XXXXXXX X XXX XX XXXXXXXX XXXX XXXXXXXX XXX
        BB BBBB BBB BBB BB BBBBBB
            XXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
            BBB B BB BBBBBB
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXBBBBBXXXXXX
				XXXXXX
			XXXXXX
            BBBBBB
            BBBB BBBB BBB BBB BB BBBBBB
            XXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXX
                BBB B BB BBBBBBB
			XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX X
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXBBBBBXXXXXX
				XXXXXX
			XXXXXX
            BBBBBB
            BBBBB
            XXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX XXX
		XXXXXX
	XXXXXX
	BBBBB



	BB BBBB
	XXXXXX XXXXXXXXXXXXXXXX
	XXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXX XXXXX XXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXX XXXXXX
    XXXXX XXXXXX
X
XXXXXXXXXXXXX XXXX
	XXXXXXXXXX XXXXX XXXXXXX XXXXX
X
XXXXXXXXX
	XXXXXXXXXXX XXXXXX
X
	XXXXXXXXXXXXXXXXXXX
		XXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXX XXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
	X
	XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX	
	X
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
			XXXXXXXXXXXX XXXXXXX XXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXX
			XXXXXXXXXXX XXXXXX
			XXXXXXXX XXXXX
		X
		XXXXX
			XXXXXXXXXXXXXX XXXXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
			XXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXX XXXXX
			XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
			XXXXXXXXXX XXXXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXX XXX XXXX XXXX X XXXXXXXXX XXXX XX XXXXX
			XXXXXXXXXX XXXXXXXXXXXX
			XXXXXXXXXXXXXX XX
			XXXXXXX XXXXXXXX
			XXXXXXXXXXXXXX XXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXX XXXX XXXX X XXXXXXXXX XXXX XX XXXXX
			XXXXXXXXXX XXXXXXXXXXXX
			XXXXXXXXXXXXXX XX
			XXXXXXX XXXXXXXX
			XXXXXXXXXXXXXX XXXX
		X
		XXXXXXXX XXXXXXXXXX X
		    XXXXXXXXXXXX XXXXXXX XXXXXX
		    XXXXXXXXXX XXXXX
		    XXXXXXXXXXXX XXXXX
		    XXXXXX XXXXXX
		    XXXXXXXXXXXXX XXXXX
		    XXXXXXXXX XXXXXXX
   			XXXXXXXXXXXX XXXXXXX
    		XXXXXXXXXXXXXX XXXXXXXXX
    		XXXXXXXXXXXXXXX XXXXXXXXXX
    		XXXXXX XXXXXX
		X
		XXXXXXXX XXXXXXXXXXXXXX X
		    XXXXXXXXXXXX XXXXXXX XXXXXXXXX
		    XXXXXXXXXX XXXXX
		    XXXXXX XXXXXXXX
		X
		XXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXXXXX XXXXXXXXXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
			XXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXX XXXXX
			XXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXX
				XXXXXXXXX XXXXXXXXX
			    XXXXXX XXXXX
			    XXXX XXXX
			X
		XXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXX
			XXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXX XXX XXXXXX XXXXXXXXXXXXXX XXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		X
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXX  XXXXXXXXXXX XXXXX
		X
		XXXXXXXX X XXX
			XXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXX X XXX
			XXXXXXXXXXXXXX XXXXX
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXX
				XXXXXX XXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX X
			    XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXX XXXXXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX XXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXX
				XXXXXXXXX XXXXXXXXX
			    XXXXXX XXXXX
			    XXXX XXXXX
			X
			XXXXXXXX XXXXXXXXXXX
				XXXXXX XXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXX XXXXXX
			X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXX
				XXXXXX XXXXXX
			X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX XXXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXX XXXXXX
			X
			XXXXXXXXX
				XXXXXXXXXXX XXXXX
			X
			XXXXXXXXX
	XXXXXXXXXXX XXXXX
X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXXX
			X
			XXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX XXXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXX XXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX X XXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXX
				XXXXXX XXXXXX
				XXXXXXXXXXX XXXXX
			X
			XXXXXXXXX
				XXXXXXXXXXXXX XXX XXXXXXXXXXX
			X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXX
				XXXXXX XXXXXX
				XXXXXXXXXXXXXX XXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX XXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXX XXXXXX
			X
			XXXXXXXXXXXXXXXXXXXXXXXXX XXX
				XXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
				XXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXXXXXX XXXX XXXXXXXXXXX
				XXXXXX XXXXXX
			X
			XXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
				XXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXX X XXX XXXXXXXX X XXX
				XXXXXXXXXXXX XXXXX
			X
			XXXXXXXXX
				XXXXXXXXXXX XXXXXX
			X
			XXXXXXXXXXXXXX
				XXXXX XXXXX
			X
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
	XXXXXXXX
	BBBB
	XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXX XXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXX XXXXXXXX XXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXX XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
				XXXXX
					XXXXXXXXXXXXXX
					XXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XX XXXX XXXXXXXXX XXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXX XXX XXXX XXXXXXXX XXXXXXX XX XXXXXXXX XX XXX XX XXX XXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXX X XXXXX XXXXXX XXXXXXX XX XXXXXXXXXXXXX
				XXXXX
					XXXXXXXXXXXXXX
					XXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX X XXXXXXXXXX XX XXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXX X XXXX XXXX XXXXXXXX XXXXXX XXXXXX XXXXXX X XXXXXXXXXXXXXX XXXXXXXXX XX XXXX XX XX XXXXXXXXX XXXXXXXXXX XXX XX XXXXXXX XXXXXXXX XXXXX XXXXXXX X XXXXXXXX XXXXXXXXXXXX X XXXX XXXX XXXXXXXX XX XXXXXXXXXXXX
				XXXXX
					XXXXXXXXX XXXXXXXXX
					XXXXXXXXXX XXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXX XXXXX XXXXX XX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX X XXXXXX XXXXXX XXXXXXXXX XXXXXX XXX XXXXXXXXXX XXXXXX X XXXXXXX XXXX XXXXXXX XXXXXXXXX XX X XXXXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXX XX XXXXXXXX XX XXXXXXXX X XX XXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXX XXXXX XXXX XXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
				XXXXX
					XXXXXXXX XXX XXX XXXXX XXXXXXXXXXXX
					XXXXXXXXXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXX XXXXXXXX XXXXX XXXX XXXXXX XXXXX XXXXXXX XXXXXXXX X XXXXX XXXXXX XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XX XXX XXXXX XXXXXXXX XX XXXXX XXXXXXXXXXX XXXXXXX XXXXX XX XXXX XX XX XXX XXXXXXX XXX X XXX XXXXXXX XXXXXX XX XXXXX XXXXXX XXXXXXXXXX XXX XX X XXX XXXXXXX XXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXXX XXXXXX XXXX XXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXX
				XXXXX
					XXXXXXXXXX XXXXXXXXXX
					XXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXX XXXX XXXXXXXXXXX XXX

	BBBBB


BBBB BBBBBBBB
    BBBBBBBB

          BBBB BBBBBBBBB
			BBBBBBB BBBBBBBBBBBBB
            BBBBBBB


XXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

BB BBBB
XXXXXXXX
	XXX XXX X XXXXXXXXXXXXX
	XXX XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXX
	 
	XXX XXXXXXXXXXX X XXXBBB B BB BBBBBBBBB XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXBB BBBBBB BB BBBBBBBBBBXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFF FF FFF XXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXBBBBBXXXXXX XXXXXX XXXXXX BBBBBBXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX
BBBBB
XXXXXXXX
	XXX XXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXX X
				  XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				  XXXXXXXXXX XXX
				  XXXXX XXXXX
				  XXXXXXXXXXX XXXXXX
				  XXXXXXXXXX XXXXXXXXX
				XXX

	XXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
				  XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXX
				  XXXXXXXXXX XXX
				  XXXXX XXXXXX
				  XXXXXXXXXXX XXXXX
				XXX

	XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX


XXXXXXXX
		        XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
		            XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
		                XXXXXXXX XXXXXXXXXXXXXXXX
		                    XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		                XX XXXXXX
		            XXX
		        XXX


		        XX XXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XX
  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
  XXX
		    XXXXXXXXX


		    XXXXXX XXXXXXXXXXXXXXXX
		    XXXXX
		    	XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
		    X
		    XXXXX X
    XXXXXXXXXXX XXXXX XXXXXXXXXXX
X
		    XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
		    	XXXXXXX XXXXXX XXXXXXX XXXXXX X
		    		XXXXXXXXXX XXXXX
		    		XXXXXXXXXXX XXXX
		    	X
		    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
		    		XXXXXXXXXXX XXXX XXXXXXXXXXX
		    	X
		    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		    		XXXXXXXXXXX XXX XXXXXXXXXXX
		    	X
		    	XXXXXXXXXXXXXX XXX
		    		XXXXXXXXXXXX XX
		    		XXXXXXXXXXX XXXXXX XXXXXXXXXXX
		    	X
		    	XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
		    		XXXXXXXX XXXXX
		    	X
		    	XXXXXXXXXXXXX
		    		XXXXXX XXXXXX
		    	X
		    	XXXXXXXXXXXXXXXXXXXXXX XXXXX
		    X
		    XXXXXXXX

		    BB BBBB
XXXXXX XXXXXXXXXXXXXXXX
XXXXXX
     		XXXXXXX XXXXX
     		XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
     	XXXXXXXXX
     	BBBBB



XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX


	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXX X XXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
		 XXXXXXXXXXXXXXXXXXXXXX
		 	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XX XXXXX
		 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
		X XXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
			XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
			XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
			XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

			XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX

		

			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXX
			 	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
			XX XXXXX
		 	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
		X
	XXX

	XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	XXX




    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XX

    XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    	    XXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBB BBBBXX
		X
		XXXXX
	        XXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBB BBBBXX
		X
    XXX

 XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    	    XXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBB BBBBXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
	XXX



XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
		XXXXXXXXXXXXXXXXXXXXXXXX X XXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X XXXXXXX 
	XXX


	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBB BBBBXX
	XX
	XXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBB BBBBXX
	XX
XXXXXXXXX
XXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXBB BBBBBBBBBBB BB B BBBBBBBBBXXXXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBBBXX
XXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX XXXX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX XX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXBB BBBBBBBBBBB BB B BBBBBBBBBXXXXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBBBXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXX X XBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
		XXX
XX XXXXXX

	XXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXBB BBBBBBBBBBB BB B BBBBBBBBBXXXXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBBBXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXX X XBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
		XXX
	XX XXXXXX

	XXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXBB BBBBBBBBBBB BB B BBBBBBBBBXXXXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBBBXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXX X XBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
		XXX
	XX XXXXXX
XX XXXXXX

XXXXXXXXX


XXXXXXX

