XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
	XXXXXXXXXXXXXX X XXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX

	XXXXX XXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXX XX
	XXXXX XXXXXXXXXXXXXXXXX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
	XXXXX XXXXXXXXXXXXXXXXXX 		  XXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXX 	  XXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXX XX
	XXXXX XXXXXXXXXXXXXXXXXXX         XXXXXXXXXX XX

    BBBB BBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
	XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXX
			XXXXXXXXXXX XXXXXX
		X
		XXXXXXXXXXXXX XXXXXXX
		    XXXXXX XXXXX
		    XXXXXXX XXXXXX
		    XXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXX XXXX
			XXXXXXXXXX XXXXXXX
			XXXXXXX XXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXXXXXXXXX XX
			XXXXXXXXXXX XXXX
			XXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXXXX XXXXXXXXX
			XXXXXX XXXXXXXX
		X
            XX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXX
    X

	XXXXXXXX
XXXXXXX
 XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXXXX
			XXXX XXXXX
			XXXXXX XXXXX
			XXXXX XXXXXX
			XXXXXXXX XXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X

		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX X
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
				XXXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXX XXXXXXXXXXX
			X
		X

	XXXXXXXX

XXXXXX
    BBBB BBBBBBBBB BBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBB
	 BBBBBBB BBBBBBBBBBBBB
BBBBBBB
	 XXXXXX XXXXXXXXXXXXXXXX
    	XXXXX
    		XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    	X
    	XXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXX
    		XXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
		X

		XXXXXXXXXXXXX X XX
			XXXXXX XXXXX
			XXXXXXXXXXXXXXXX XXXXXXXXXX
		X

		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXX
				XXXXXXXXXXX XXXXX XXXXXXXXXXX
			X
		X
		XXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX X
			    XXXXXXXXXXXX XXXXX
			X
			XXXXXXXXXXXX
				XXXXXXXX XXXXX
			X
			XXXXXXXXXXXX
				XXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX

		X
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XX XXXXXXBBB BBBBBBXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                BB BBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXX
                BBBBB
            XXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
				XXXXXXXXXXX
				XXXXX
					XXXXXXXXXXXXX
					XXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXX XXXXXX  XXXXXXXXXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
				BBBBBBB BBBBBBBBBBBBBBBB
		
		XXXX XXXXXXXXXXXXXXXXXXXXX

            FFFF

		XXXXXX
		XXXX XXXXX XXX
		BBBBBBB BBBBBBBBBBBBBBBB



	XXXXXX

        XXXXXX
    XXXXXX
    
            BBBB BBBBBBBBB
			BBBBBBB BBBBBBBBBBBBB
            BBBBBBB

    BBBB BBBBBBBB
BBBBBBBB
XXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXX XXX
XXXXXXXXX
	XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX

		XXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX



    XXXXXXXXX

    XXXXXXXX
   
    XXX XXXXXXXXXXXX X XXX
	
	XXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBXX XXXXXXXXX

XXXXXXX