XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXXXXXXXXXXX X XXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX

    BBBB BBBBBB

	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
 XXXXXXX

 XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXXXX
			XXXX XXXXX
			XXXXXX XXXXX
			XXXXX XXXXXX
			XXXXXXXX XXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X

		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX X
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
				XXXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXX XXXXXXXXXXX
			X
		X

	XXXXXXXX

BBBB BBBBBBBBB BBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBB
    BBBBBBB

    XXXXXX XXXXXXXXXXXXXXXX
    	XXXXX
    		XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    	X
    	XXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXX
    		XXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXX
				XXXXXXXXXXX XXXXX XXXXXXXXXXX
			X
		X
    XXXXXXXX


  	XXXXXXX
	    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
	    XXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXX XXXX
		    XXXXXXXXXXXXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
	XXXXXXXX


BBBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

	XXXX XXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XX XXXXXXBBB BBBBBBXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX
			BB BBBBBBBBBBB
				XXXX XXXXXXXXXXXXXXXXXXXXX
	               XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXBB BBBBBBBBBBB  BBBBBXX
				XXXXXX
			BBBB
				XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	               XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
			BBBBB

			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
				XXXXXXXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXXXXXXXXXXX
			XXXXXX
			XX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXX XXXXXXXXX
            XXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXX
                XXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
				XXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBB BB BBB BBBB
		          FFFF
            BBBBB
        XXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXXXX
		XXXXXX

		XXXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
			    XXXXXXXX XXXXX
			    XXXXXXXXXXXXXXX XXXXXXX
			    XXXXXXXXXXXX XXXXXXXXXXX
			X
			XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
				XXXXXXXXXXXX X XXXXXXXXXXX
			X
		XXXXXXXX

        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BBB B BB BBBBB

                XX XXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX
            XXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX

						XXXXX
                            BB BBBBBB BB B BBBB BB BBBBBBBBBB BB B XXXXXX BBBB BBBBBBBBBB BB B XXXXXXXXX BBBB XXXXXXXXXXX BBBBB BBBBBXXXXXX
						XXXXX
							XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
							XXXXX XXXXXXXXXXXXX XXXXXXX
								XXXXXXXXXXXXX
								X 
							XXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
                XXXXXX
			XXXXXX
                XXXX
            BBBBBB
        XXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX
						XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
						XXXXX
							XXXXXXXXXXXXXXXXXXXXXX
							XXXXXX
								XXXXXXXXXXX XXXXXXXXX
								XXXXXXX XXXXX X XXXXXXXXXXX
							XXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX
						XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
						XXXXX
							XXXXXXXXXXXXXXXXXXXXXX
							XXXXXX
								XXXXXXXXXXX XXXXXXXXX
								XXXXXXX XXXXX X XXXXXXXXXXX
							XXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX
						XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
						XXXXX
							XXXXXXXXXXXXXXXXXXXXXX
							XXXXXX
								XXXXXXXXXXX XXXXXXXXX
								XXXXXXX XXXXX X XXXXXXXXXXX
							XXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX
						XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
						XXXXX
							XXXXXXXXXXXXXXXXXXXXXX
							XXXXXX
								XXXXXXXXXXX XXXXXXXXX
								XXXXXXX XXXXX X XXXXXXXXXXX
							XXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
				XXXXXX
			XXXXXX
			XXX
			XXXX XXXXXXXXXXXX
		XXXXXX
    BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
			XXXX BB BBBB B B XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXX  X
					XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX BB BBBB BB BBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXX XXX
					XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
    BBBBBBB
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
				BBB B BB BBB

                    BB B BB BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                BBBBBB
			XXXXXX
		XXXXXX
	XXXXXX


    BBBB BBBBBBBBB
			BBBBBBB BBBBBBBBBBBBB
            BBBBBBB

BBBB BBBBBBBB
BBBBBBBB
BBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX X XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX X XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
	X

XXXXXXXXX
XXXXXXX
