XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
	XXXXXXXXXXXXXX X XXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXX XX
	XXXXX XXXXXXXXXXXXXXXXX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
	XXXXX XXXXXXXXXXXXXXXXXX 		  XXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXX 	  XXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXX         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXX XX XXXXXX XX
	BB BBBBBBBBB BB B 	
	XXXXX XXXXXXXXXXXXXXXXXXX         XXXXXXXXXX XX
	BBBB
	XXXXX XXXXXXXXXXXXXXXXXXX         XXXXXXXXXX XX
	BBBBB


	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX
    BBBB BBBBBB

  


  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
	XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXXXX XXXX
			XXXXXXXXXX XXXXXXX
			XXXXXXX XXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXXXXXXXXX XX
			XXXXXXXXXXX XXXX
			XXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXXXX XXXXXXXXX
			XXXXXX XXXXXXXX
		X
            XX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXX
    X

	XXXXXXXX
XXXXXXX
 XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXXXX
			XXXX XXXXX
			XXXXXX XXXXX
			XXXXX XXXXXX
			XXXXXXXX XXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
		
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX X
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
				XXXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXX XXXXXXXXXXX
			X
		X

	XXXXXXXX

XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX XX XXX X
  XXX XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
  XX X XXXXXXXXXXXXXXXXXXX XXXXX X XXX
  XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

    BBBB BBBBBBBBB BBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBB
	 BBBBBBB BBBBBBBBBBBBB
BBBBBBB
	 XXXXXX XXXXXXXXXXXXXXXX
    	XXXXX
    		XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    	X
    	XXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXX
    		XXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXX
				XXXXXXXXXXX XXXXX XXXXXXXXXXX
			X
		X
		XXXXXXXXXXXXXXX XXXXXXXXX X
		    XXXXXXX XXXX XXXXXXXXXXX
		    XXXXXXXXXXX XXXXXX
		X
		XXXXXXXXXX XXX
			XXXXXXXXXXX XXXXXXX
		X
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XX XXXXXXBBB BBBBBBXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXX
                BBBBB
            XXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
				XXXXXXXXXXX
				XXXXX
					XXXXXXXXXXXXX
					XXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXX XXXXXX  XXXXXXXXXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX XXXXXXXX BB BBBBBBBBB BB B  BBBBBBBBBXXXXX
				XXXXXXXXXXX XX XXXXX  XXX XXXX X XXX XXXXXXX
				BBBBBBB BBBBBBBBBBBBBBBB

		XXXX	XXXXXXBB BBBBBBBBBBBBBBB
			XX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX XXX XXXXX
            XXXXXXXXXX
        BBBBB
		XXXXXX XXX

    	XXXXXXBB BBBBBBBBBBB BB BBBB
        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBB BBBBBBBBBBBBBBXX
        BBBBBBBBBB
			XX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXX
            XXXXXXXXXX
        XXXXXXX
        BBBBB
		XXXXXX


        XXXX XXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXBB BBBBBBBBB BB B BBBBBBBBBXXXXX
				XXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
			XXXXXX
            BB BBBBBBBBB BB B
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXXXXXXXXX
				XXXXXXXXX XXXXXXXXXXXX
			XXXXXX

			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXX XXXXXXXXXX
			XXXXXX
		
        BBBBB
        BB BBBBBBBBB BB B BBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB


			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXXXXXXXX
				XXXXXXXXXX XXXXXXXXXXX
			XXXXXX
        BBBBB
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXX

            FFFF


		XXXXXX
		XXXX XXXXX XXX
		XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
			BBBBBBB BBBBBBBBBBBBBBBB

	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			BB BBBB
			XXXX XXXXXXXXXXXXXXXXXX
                    BB BBBBBBBB

				XXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXX
					XXXXXXXXXXXXXXX XXXXXXXXXXXX
					XXXXXXXXXXXXX
				XXXXXX
                                    BBBBB


			XXXXXX
            BB BBBB BB BBB BBBB
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
			BBBBB
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                    BB BBBBBBBB

				XXXX XXXXXXXXXXXXXXXXXXX XXX
					XXXXXXXXXXXXXX XXXXXXXXXXXX

					XXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX

				XXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXX  XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
                    BBBBB

			XXXXXX
			BBBBB
		XXXXXX
	XXXXXX

            BBBB BBBBBBBBB
			BBBBBBB BBBBBBBBBBBBB
            BBBBBBB

    BBBB BBBBBBBB
BBBBBBBB
XXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXX XXX
XXXXXXXXX
	XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX

		XXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX



    XXXXXXXXX


    XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXX
    XXX XXXXXXXXXXXX X XXX
	XXXXXXXXX

    XXXXXXX XXXXXBBBBBB BBBBBBBBBBXX XXXXXXXXX
XXXXXXX