XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    BB BBBBBBB BB BBB
    XXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXX
    BBBB
    XXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXX
    BBBBB
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX

    BBBB BBBBBB

	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
 XXXXXXX

 XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXXXX
			XXXX XXXXX
			XXXXXX XXXXX
			XXXXX XXXXXX
			XXXXXXXX XXXX
		X

		XXXXXXXXXXXXX XXXX
			XXXXXXXXXX XXXXXXX
			XXXXXXX XXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXX XXXX
				XXXXXXXXXX XXXXXX
			X
		X


		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX
				XXXXX XXXXXX
			X
		X
		
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXX X
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
				XXXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXX XXXXXXXXXXX
			X
		X


		XX XXX XX

		XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXX
		X

		XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXX
		X

	XXXXXXXX

BBBB BBBBBBBBB BBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBB
    BBBBBBB

    XXXXXX XXXXXXXXXXXXXXXX
    	XXXXX
    		XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    	X
    	XXXXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXXXX
    		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    	X
    	XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXX
    		XXXXXXXX XXXXX
    	X
    	XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
		X
		XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXX
				XXXXXXXXXXX XXXXX XXXXXXXXXXX
			X
		X
    XXXXXXXX


  	XXXXXXX
	    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
	    XXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXX XXXX
		    XXXXXXXXXXXXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXX
			XXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
		X
	XXXXXXXX
	XXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXX X XXXXXXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXX XXXXX  XXXXXXXXXXX
		    XXXXXXX XXXXX
		    XXXXXXXXXXX XXXXXX
		    XXXXXXXXX XXXXXXXXX
		    XXXXXXXXXXXX XXX  XXXXXXXXXXX
		    XXXXXXXXXXX XXXXX  XXXXXXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXX XXXXX  XXXXXXXXXXX
		    XXXXXXX XXXX
		    XXXXXXXXXXX XXXXXX
		    XXXXXXXXX XXXXXXXXX
		    XXXXXXXXXXXX XXX  XXXXXXXXXXX
		    XXXXXXXXXXX XXXX  XXXXXXXXXXX
		X
		XXXXXXXXXXXXX
			XXXXXXXXXXXXX XXXX XXXXXXXXXXX
			XXXXXXXXXXXX XXXX  XXXXXXXXXXX
		X
		XXXXXXXXXXXXX XXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXX
			XXXXXXX XXXXXXXX
		X
		XXXXXXXXXX XXXXXXXXXXXXX
			XX X
			    XXXXXXXXXXXX XXXX
			X
			XXXX X
			    XXXXXXXXXXXX XXXXXX
			X
		X
		XXXXXXXXXX XXXXXXXXXXXXXX
			XX X
			    XXXXXXXXXXXX XXXXXX
			X
			XXXX X
			    XXXXXXXXXXXX XXXX
			X
		X
		XXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
			    XXXXXXXXXXXX XXXXX
			X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXX
			    XXXXXXXXXXX XXXXXX
			X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXX
			    XXXXXXXXXXX XXXX
			X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXX XXXX XXXXXXXXXXX
			    XXXXXXX X XXXXXXXXXXX
			    XXXXXXXXXXX XXXX XXXXXXXXXXX
    			XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
			X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXX
			    XXXXXXXXXXX XXXXXX
			X
			XXXXXXXX XXX
				XXXXXXXXXXXXXX XXXXX
			X
			XXXXXXXXXXXXX XXXXXXXXXXXXXX
				XXXXXXXXXX XXXXX
			X
			XXXXXXXXXXXXX
				XXXXXXXXXXX XX
			X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXX XXXXX
			X
			XXXXXXXXXXXX X
				XXXXXX XXXXXX
			X
			XXXXXXXXXX
				XXXXXXXXXXXX XXXXX
			X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXX XXX
				XXXXXXXX XXXXXX
			X
			XXXXXXXXXX
				XXXXXXXXXXX XXXXXX
			X
			XXXXXXXXXX
				XXXXXXXXXXXX XXXXX
			X
			XXXXXXXXXXXXXXXXX
				XXXXXXXXXX XXXXX
			X
			XXXXXXXXXXXXXXXX
				XXXXXXXXXXX XXXXXX XXXXXXXXXXX
    			XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
			X
			XXXXXXXXXXXX
				XXXXXXXX XXXXX
			X
		X
		XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
			XXXXXXXXX
				XXXXXXXXXXX XXXX XXXXXXXXXXX
			X
			XXXXXXXXXXXXXXXX X XXXX
				XXXXXXX X XXXXXXXXXXX
				XXXXXXXXXXX XXX XXXXXXXXXXX
    			XXXXXXXXXXXX XXX XXXXXXXXXXX
			X
		X
		XXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXX
		X
	XXXXXXXX


BBBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

	XXXX XXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XX XXXXXXBBB BBBBBBXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX  
			BB BBBBBBBBBBBB
				XXXX XXXXXXXXXXXXXXXXXXXXX
	               XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXBB BBBBBBBBBBBB  BBBBBXX
				XXXXXX
			BBBB
				XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	               XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
			BBBBB

			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXX XXXXXXXXXXXX
				XXXXXXXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
            BB BBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXX XXXXXXXXX
            XXXXXXXXXXBBBB XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXX XXXXXXXXX
            XXXXXXXXXX BBBBB
		XXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				BB BBBBBBBBBBBBBBBBBBBBB B B BB BBBBBBBBBBBBBBBBBBBBB BB BBBB XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BBBBXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBB
				XXXXXXX XXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXX
                XXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
				XXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBB BB BBB BBBB
		          FFFF
            BBBBB
        XXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXXXX
		XXXXXX

		XXXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
			    XXXXXXXX XXXXX
			    XXXXXXXXXXXXXXX XXXXXXX
			    XXXXXXXXXXXX XXXXXXXXXXX
			X
			XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
				XXXXXXXXXXXX X XXXXXXXXXXX
			X
		XXXXXXXX

        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
			
			
			BB BBBBBBBBBBBBBBBBBBBBB BB B
			BBBB
			BBBBB
			

            BBB B BB BBBBB

                XX XXXXXBBB BBBBBBBBBB BBBBBBBBBB BBBBBBBBBBX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX

						XXXXX
                            BB BBBBBB BB B BBBB BB BBBBBBBBBB BB B XXXXXX BBBB BBBBBBBBBB BB B XXXXXXXXX BBBB XXXXXXXXXXX BBBBB BBBBBXXXXXX
						XXXXX
							XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
							XXXXX XXXXXXXXXXXXX XXXXXXX
								XXXXXXXXXXXXX
								X 
							XXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
                XXXXXX
			XXXXXX
                XXXX
            BBBBBB
      
			XXXXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
					XXXXXXXXXXXX X XXXXXXXXXXX
					XXXXXXXXXXX XXXXX
				X
			XXXXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
				BBB B BB BBB

                    BB B BB BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                BBBBBB
			XXXXXX
		XXXXXX
		XXXXXX
    BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
			XXXX BB BBBB B B XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXX  X
					XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX BB BBBB BB BBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXX XXX
					XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
    BBBBBBB
	XXXXXX

	XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
			XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
			XXXXXX
		XXXXXX

		XXXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
			    XXXXXXXX XXXXX
			    XXXXXXXXXXXXXXX XXXXXXX
			    XXXXXXXXXXXX XXXXXXXXXXX
			X
			XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
				XXXXXXXXXXXX X XXXXXXXXXXX
				XXXXXXXXXX XXXXX
			X
			XXXXXXX
				XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX XXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX
			X
			XXXXXXX
				XXXXXXX XX
				XXXXXXXXXXXX XXXXXX XXXXXXXX
			X
			XXXXXXXXXXX X XXX X XXX X
				XXXXXX XXXXXX
			X
			XXXXXX XXXX
				XXXXXXXXXX XXXXXX
				XXXXXXXXXXXXXX XXXX
				XXXXXXXXXXX XXXXXX
    			XXXXXXXXXXX XXXXXX
				XXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXX XXX XXXXXX
			X
		XXXXXXXX

		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
			
			
			BB BBBBBBBBBBBBBBBBBBBBBB BB B
			BBBB
			BBBBB
			
			
            BBB B BB BBBBBB

                XX XXXXXBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX

            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX

						XXXXX
							
                        XXXXXX
						XXXXX
							XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
							XXXXX XXXXXXXXXXXXX XXXXXXX
								XXXXXXFFFFFFFFFFFFFXXXXXXX
							XXXXXXX
							XXXXX XXXXXXXXXXXXX XXXXXXX
								BB BBBB BB BBBBBBBB
								XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXBBB BBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
								XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
								BBBBB
							XXXXXXX
						XXXXXX
                        

					XXXXXX
                    BB BBBBBBB
					XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                    BBBBB
                XXXXXX
			XXXXXX
                XXXX
            BBBBBB
      
			XXXXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
					XXXXXXXXXXXX X XXXXXXXXXXX
					XXXXXXXXXXX XXXXX
				X
			XXXXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
				BBB B BB BBBBB

                    BB B BB BBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX


                    BBBBB
                BBBBBB
			XXXXXX
		XXXXXX
		XXXXXX
    BBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
			XXXX BB BBBB B B XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXX  X
					XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX BB BBBB BB BBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXX XXX
					XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
    BBBBBBB
	XXXXXX

    BBBB BBBBBBBBB
			BBBBBBB BBBBBBBBBBBBB
            BBBBBBB

BBBB BBBBBBBB
BBBBBBBB
BBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX



    XXXXXXXX XXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    X

    XXXXXXXX XXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    X

	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XX	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
XX

	    XXXXXXXXXX

	XXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XX	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
	XX

	XXXXXXXXXX

	XXX

	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX


	XXX XXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXX
        XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXX
        XXXXXXXXXX


XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX X XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX X XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
	X

	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX X XXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX X XXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X XXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXX X XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX X XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X

	XXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XX
XXXXXXXXX
XXXXXXX
