XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXXXXXXXXXXX X XXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX

    BBBB BBBBBB

	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
 XXXXXXX

  XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXX


BBBBB BBBB

	XXXX XXXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XX XXXXXXBBB BBBBBBXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
				XX XXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX
			BB BBBBBBBBBBB
				XXXX XXXXXXXXXXXXXXXXXXXXX
	               XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXBB BBBBBBBBBBB  BBBBBXX
				XXXXXX
			BBBB
				XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	               XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX
			BBBBB


			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
				XXXXXXXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				BB BBBBBBBBBBBBBBBBBBBBB B B BB BBBBBBBBBBBBBBBBBBBBB BB BBBB XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BBBBXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBB
				XXXXXXX XXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXX
                XXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
				XXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBB BB BBB BBBB
		          FFFF
            BBBBB
        XXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXXXX
		XXXXXX

		XXXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
			    XXXXXXXX XXXXX
			    XXXXXXXXXXXXXXX XXXXXXX
			    XXXXXXXXXXXX XXXXXXXXXXX
			X
			XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
				XXXXXXXXXXXX X XXXXXXXXXXX
			X
		XXXXXXXX

        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX

        BB BBBBBBBBBBBBBBBBBBBBB BB B XXX XXXX XXXXXXXX XXXXXXXXXX BBBBB

            BBB B BB BBBBB

                XX XXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBX
            XXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX

						XXXXX
                            BB BBBBBB BB B BBBB BB BBBBBBBBBB BB B XXXXXX BBBB BBBBBBBBBB BB B XXXXXXXXX BBBB XXXXXXXXXXX BBBBB BBBBBXXXXXX
						XXXXX
							XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
							XXXXX XXXXXXXXXXXXX XXXXXXX
								XXXXXXXXXXXXX
								X 
							XXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
                XXXXXX
			XXXXXX
                XXXX
            BBBBBB
        XXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX
						XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
						XXXXX
							XXXXXXXXXXXXXXXXXXXXXX
							XXXXXX
								XXXXXXXXXXX XXXXXXXXX
								XXXXXXX XXXXX X XXXXXXXXXXX
							XXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX
						XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
						XXXXX
							XXXXXXXXXXXXXXXXXXXXXX
							XXXXXX
								XXXXXXXXXXX XXXXXXXXX
								XXXXXXX XXXXX X XXXXXXXXXXX
							XXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX
						XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
						XXXXX
							XXXXXXXXXXXXXXXXXXXXXX
							XXXXXX
								XXXXXXXXXXX XXXXXXXXX
								XXXXXXX XXXXX X XXXXXXXXXXX
							XXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XXXXX
					XXXXX
						XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
						XXXXX
							XXXXXXXXXXXXXXXXXXXXXX
							XXXXXX
								XXXXXXXXXXX XXXXXXXXX
								XXXXXXX XXXXX X XXXXXXXXXXX
							XXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
				XXXXXX
			XXXXXX
			XXX

		XXXXXX
		BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
			XXXX BB BBBB B B XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXX  X
					XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX
			XXXXXX
			XXXX BB BBBB BB BBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXX XXX
					XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
				XXXXXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
    BBBBBBB

		XXXX XXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB B B
			XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
				BBB B BB BBB

                    BB B BB BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBBBB
                BBBBBB
			XXXXXX
        BBBBB
		XXXXXX

	XXXXXX
BBBB BBBBBBBB
BBBBBBBB
BBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX X XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX X XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
	X

	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX X XXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX X XXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X XXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXX X XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX X XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	X


	XXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX


XXXXXXXXX
XXXXXXX