BBBBBBBBBB BBB
XXXXXXX X


XXXXX XXXXXX XXXXX XXXXXX XXXXXXX XXXXXXXX XXX XXXXXXXX XXXXXXXXX XXXX XX XXXX XXXXXXXXX XX XXX XXXXX X XXXX XXXX XXXX
XXXXXXXXXXXX XXXXXXXXX

    XXXXXXXX XXX XXXXXXXX XXXXXXXXXX

    BBB B BB BBBBB

          X 

    BBBBBB

BBBBBBBBBBBBB