XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    BBBB BBBBBB
	XXXXXXXXXXXXXX X X XXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBXX XXXX XXXXXXX XX XXXXXXX XXXXXXXXXXXX XXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX XXXX XXXXXXX XX XXXXXXX XXXXXXXXXXXX XXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX XXXX XXXXXXX XX XXXXXXX XXXXXXXXXXXX XXX

    XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX

		BBBB BBBBBBBBB BBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBB

		BBBBBBB BBBBBBBBBBBBB
		
		BBBBBBB

XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
			XXXXX
				XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXXXXXXXXXXXXXX
				XXXXXXX XXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXX
				XXXXXXXXXX XXXXXXXXXX
				XXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXX XXXXX XXXXX XXX XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XX XXXX XXX XXXXX XXXXXXXX XXXXXXXX XXX XX XXX XXXX XXXXX XXXXXXXX XX XXX XXXXXXXXX XXXXXXXXXXX XXX XXXXX XXXXXX XXX XX XXX XXXXXX XXXXXXX XX XXXXXX XXXXXXX XXXX XX XXXXX XXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXX XXX XXX XXXXXX XXXXXX XXXXXXX XXX XX XXXXX XXXXXXX XXXXXXXXXX XXXX XXX XX XXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXX XXXXXXX
			XXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XX XXXX XXXXXXXX XXXXXXXXXX XX XXXX XXX XXXXX XXXXXX XXX XX XXXXX XXXXXXX XXXXXXXXXX XXXX XXX XXXXXX XXXXXXXXX XXXXXXXXX XXX XXX XXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXX XXX XXX XX XXXXX XXXXXXX XXXX XX XXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXX XX XXXX XX XXXXXXX XXXXXXXX XXXX XX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXX XXX XXXXXX XXXXXX XXXXXXXXXX XXX XXX XXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XX XXX XXXXXX XXXXXXX XXXXXXXXXXXXX
		XXXXXX
			XXXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
			    XXXXXXXX XXXXX
			    XXXXXXXXXXXXXXX XXXXXXX
			    XXXXXXXXXXXX XXXXXXXXXXX
			X
			XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
				XXXXXXXXXXXX X XXXXXXXXXXX
			X
			XXXXXX
				XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
				XXXXXXXXXXX XXXXX
				XXXXXX XXXXX
				XXXXXXXXXXXXX XXXXXX
				XXXXXXX XXXXX
			X
			XXXXX XXXX
				XXXXXXXXXX XXXXXX
				XXXXXXXXXX XXXXXX
			X
			XXXXXXXXXXXXX XX
				XXXXXXXXXXXXXXXX XXXXX
				XXXXXX XXXXXXXX
			X
			XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXXX X
			    XXXXXXXXXXXXXXXXXXXXXXX XXXX
			    XXXXXXXXXXXXXXXXXXXXXXXX XXXX
			X
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
			    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
			    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
			X
			XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXX XXXXX
			    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
			X
			XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
			    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
			X
		XXXXXXXX

		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
			XXXX XXXXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXX XXXX XXXX XX XXXXXXX XXXXX XXX
                XXXX XXXXXXX XXXXXXXXXXXX
					XXXXX
						XXXXX
							XXXXXXXXXXX XXXX XXX XXXXXXXXX XXX
							XXXXX
							   XXXXXXXXXXXXX XXXX XXXXXXXXXX XXX XXXXX XX XXXXXXXXXXXX XXX
                                    XXXXXX
									XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXX XXX XXX
                                    XXXX XXXXXXXXXXXX XXXXXXXX XXXXX XXX
								XXXXXXX
                            XXXXXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXX
		XXXXXX
	XXXXXX



BBBB BBBBBBBBB
			BBBBBBB BBBBBBBBBBBBB
            BBBBBBB

XXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX XXXX XXXXXXX XX XXXXXXX XXXXXXXXXXXX XXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XX
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX
XXXXXXX