XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    BBBB BBBBBB
	XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBXX
	XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX

        XX
            XXXXXXXXXXXXXXXX XXXXX
        X

    XXXXXXXX

XXXXXXX
XXXXXX
XXXXXX XXXXXXXXXXXXXXXX
	XX X XXXXXXXXXXX XXXX X
	XXXXXXXXXX X
		XXXXXXXX XXXX
		XXXXXX XXXXXXXX
  		XXXXXXXX XXXXXXXXXXXXX
  		XXXXXX XXXX
  		XXXXXXXXXXXX XXXX
  	X
	XXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXX XXXXXX
		XXXXXXX XXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXX XXXXX
		XXXXXX XXXXXX
		XXXXXXXX XXXXXXXXXXXXXXXX
		XXXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXX XXX XXX XXXXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXX
		XXXXXXXXXXXXXXXXX XXXXXX
	X
	XXXXX XXX
    	XXXXXXXXXX XXXXX
    	XXXXXX XXXXXXXX
    	XXXXXXXXXXXX XXXXXXX XXXXXXXXX
    	XXXXXXXXXXXX XXXXX
	X
	XXXXX XXXXXXXXXXXXXXXX
    	XXXXXXXXXXXXXX XXXXX
    	XXXXXXXXXXXX XXXXX
	X
	XXXXX XXXXXXXXXXXXXXXX
    	XXXXXXXXXXXXXX XXXXX
    	XXXXXXXXXXXX XXXXX
    X
	XXXXX XX X XXXX X
    	XXXXXXXXXXXX XXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXX
  		XXXXXXX XXXXXX
  		XXXXXXXXXXXXXX XXXXX
  		XXXXXXXXXXXXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXX XXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXXX
		XXXXXXX XX
		XXXXXXXX XX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXX
		XXXXXXXXXXX XXXXX
		XXXXXXXX XX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX
		XXXXXX XXXXX
  		XXXXXXX XXXXX
  		XXXXXXXXXXXXXX XXXX
  		XXXXXXXXXXXXXXXXX XXXXXXXX
  		XXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXX XXX XXXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXXX XXXXX
  		XXXXXXXXXX XXXXX
  		XXXXXXXXXXXX XXXXXXX XXXXXX
  		XXXXXXXX XXXXX
  		XXXXXXXXXXXXXXXX XXXXXXX
  		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXX
		XXXXXXXXXXXXXX XXXXX
  		XXXXXXXXXXXXXXXXX XXXXXXXX
  		XXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXX XXXXXXX
		XXXXXXX XXXXXX
		XXXXXX XXXXXXX
		XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXX
		XXXXXXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXX XXXXX
  		XXXXXXXXXXXX XXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXXX XX
  		XXXXXXXXXXXX XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXX
		XXXXXXXXXXXXX XXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXX XXXXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXX
		XXXXXXXX XXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXX
		XXXXXXX XXXXX
		XXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXX XXX XXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXX
 	 	XXXXXXX XXXXX
  		XXXXXXXXXXXXXX XXXX
  		XXXXXXX XXXXX XXX XXXXXXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXXX XXXXXXX XXXXXX
  		XXXXXXXXXXXX XXXXX
  		XXXXXXXXXX XXXXXXX
  		XXXXXXXX XXXXX
  		XXXXXXXXXXXXXXXX XXXXXXX
  		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXX XXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXX XXXXX
		XXXX XXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXXXX XXXXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXXX XXXXX
		XXXX XXXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX XXXXX
		XXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXX XX
	X
	XXXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXX
		XXXXXXXXX XXXXXXXXX
		XXXX XXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXX XXX
  		XXXXXXXXXXXX XXXXXXX XXXXXXXX
  		XXXXXXXXXX XXXXX
  		XXXXXXXXXXXX XXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXX XX
  		XXXXXXXXXXXX XXXXX
  		XXXXXXXXXXXXXX XXXXX
	X
	XXXXXX
		XXXXXX XXXXXXX
		XXXXXXX X XXXXX
	X
	XXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXX
  		XXXXXXX XXXXX
  		XXXXXXXXXXXXXX XXXX
  		XXXXXXXXXXXXXXXXX XXXXXXXX
  		XXXXXXXXXXX XXX XXX XXXX X XXXXXXX XXXX XXXX XXXXXX
  		XXXXXXXX XXXXX
  		XXXXXXXXXXXXXXXX XXXXXXX
  		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXXX XXX XXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
	X
	XXXXXXXXX X XXXXXXXXXXXXXXXXX
		 XXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XXXX XXXXXX
		 XXXXXXXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXX X XXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXXXX
	X
	XXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXX
		XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
	X
	XXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXXXXXX XXXXX
  		XXXXXXXXXXXX XXXX
  		XXXXXXXXXXXX XXXXX
  		XXXXXX XXXXXXXX
  		XXXXXXXXXXXX XXXXXXX XXXXXXXX
  		XXXXXXX XXXXXXXX
	X
	XXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
		XXXXXXXXXXX XXX XXX XXX X XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
		XXXXXXXXXXX XXX XXX XXXX X XXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXXXXXX X XXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXX
		XXXXXXXX XXXXX
		XXXXXX XXXXXX
		XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
		XXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXXX XXX XXXXX XXXXXXXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
		XXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
		XXXXXXX XXXXXXXX
	X
	XXXXXXXXXXX
		XXXXXXX X XXXXX
		XXXXXXXXXXX XXXXX
		XXXXXXXXXXX XXX XXXX XXXXX X XXXXXXXX XXX XXX XXXXX
		XXXXXXXXX XXXXXXXXX
		XXXXXXXX XXXXXXXXXXX
	X
	XXXXXXX
		XXXXXXX XXXXX
		XXXXXX XXXXX
	X
	XXXXXXXXXXXXXXX
		XXXXXX XXXXXXX
		XXXXXXX X XXXXX
		XXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXXXX
	X
	XXXXXXXXXX XXXXXXXXXXX
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXX XXXXXXXXXXX
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXX XXXXXXXXXXX
		XXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXXXX XXXX
	XXXXXXXXXXXXXXXXXXX XXXX
	XXXXXXXXXXXXXXXXXX XXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
  		XXXXXXXXXXX XXX XXXX XXXX X XXXXXXXXX XXXX XX XXXXX
  		XXXXXXXXXXXXX XXXXX
  		XXXXXXXXXXXX XXXXXX
  		XXXXXXXXXXXXXX XXXX
  		XXXXXXXXXXXXXX XXXXX
	X
	XXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
		XXXXXXX XXXXXX
		XXXXXXXXXXX XXXXXXX
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXX XXXXXXXXX
		XXXXXXXXXXXX XXXXX
  		XXXXXXXXXXXXXXX XXXXX
	X
	XXXXXXX XXXXX
		XXXXXX XXXXXXXX
		XXXXXXXXXX XXXXXXX
  		XXXXXXXXXXXX XXXX
  		XXXXXXXXXXXX XXXXXXX XXXXXXXX
  		XXXXXXXXXXXX XXXX
	X
	XXXXXXXXXXXXXXXXXX
	    XXXXXX XXXXXX
	    XXXXXXX XXXXX
	    XXXXXXXXXXXXXX XXXX
	    XXXXXXXXXXXXXXXXX XXXXXXXX
	    XXXXXXXXXXXX XXXXXXX XXXXXXX
	    XXXXXXXXXX XXXXX
	    XXXXXX XXXXXXXX
	    XXXXXXX XX
	    XXXXXXXX XXXXX
	    XXXXXXXXXXXXXXXX XXXXXXX
	    XXXXXXXXXXXX XXXXXXX
	    XXXXXXX X XXXXX
	    XXXXXXXXXXX XXXXXX
	    XXXXXXXXXXXXXX XXXXX
	X

    	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXX XXX
			XXXXXXXXXX XXXXX
		X
		XXXXX XXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXX
		    XXXXXXXXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX
			XXXXXXXXXX XXXXX
			XXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXX XXXXX
			XXXXXXX XXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXX XXXXX
			XXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXX XXX
			XXXXXXXXXX XXXXX
			XXXXXXXXXXXX XXXXXX
		X
		XXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXXX
		X
		XXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXXX
		X
		XXXXXX
			XXXXXX XXXXX
		X
		XXXXXXXX
			XXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
		XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXX XXXXX XXXXXXXXXXX
		X
		XXXXXXX XXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXX
			XXXXXXXXXXXX XX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXX
			XXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXX XXXXX
			XXXXXXXX XXXXX
			XXXXXXXXXXXXXXX XXXX
			XXXXXX XXXXX
			XXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXX XXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
		X
		XXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXX XXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXX
		XXXXX XXX
			XXXXXXXXXXXX XXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXXXXXXXXXX X XXXX
			XXXXXXXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXX
			XXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXX XXXXXXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXX X XXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXXX
			XXXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XX
		X
		XXXXXXXXXXXXXXX
			XXXXXX XXXXXX
			XXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XX
			XXXXXXXXXXX XXXXXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXX
			XXXXXX XXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXX XXXXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXX XXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    		XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		    XXXXXXXXXXXXXXXXXXXXXXXX XXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXX
			XXXXXX XXXXXX
		X
		XXXXXXX
			XXXXXXX XXXXX
			XXXXXXXXXXX XXXX
		X
	X
	XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX
		XXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXX XXX
			XXXXXXXXXXXX XXXXX
		X
		XXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXX
			XXXXXXXX XX
			XXXXXXXXXX XXXXXXXXXXX
			XXXXXX XXXXX
		X
		XXXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXXXXXX XXXX
			XXXXXXXX XXXXXX
		X
	X
    XXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
    X
XXXXXXXX
BBBB BBBBBBBBB BBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBB
BBBBBBB

	XXXX XXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXX
						XXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXX XXXX XXXXXX XX XXXX XXXX XXXXXXXX XXX
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXX
						XXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXX  XXXX XXXXXX XX XXXX XXXX XXXXXXXXX XXX
					XXXXXX
				XXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                BBB B BB BBBBBBBBBBBB
               XXXX XXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXX
					XXXXX
						XXXXX
							
						XXXXXX
						XXXXX
							XXXXXXXXXXX
							XXXXXFFFFFFFF FF FFF  XXXXX BB BBB BBBBBBBBBB XXXXXXXXXXXXXXXXXX XXXXXXXBBBBB XBB BBBBBBBBBB BBBB XXXXXXXXXBBBBBXXXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXX XXXX XXXXXX XXXX XXXXXXXXXX XXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX
						XXXXXXXXXXX XXXX XXXX XXXXX XX XXXXXX XXXXXXX XXX
					XXXXXX
					XXXXX
						XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX
				XXXXXX
                BBBBBB
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBB B BB BBBBBBBBBBBBB
				XXXXX
					XXXXX
						XXXXX
							
						XXXXXX
						XXXXX
							XXXXXXXXXXX
                            XXXXXFFFFFFFF FF FFFXXXXX BB BBB BBBBBBBBBB XXXXXXXXXXXXXXXXXX XXXXXXXBBBBB XBB BBBBBBBBBBBBBB XXXXXXXXXBBBBBXXXXXXXXXXXXX

						XXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXX XXXX XXXXXX XXXX XXXXXXXXXX XXX
						XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX
						XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX
						XXXXXXXXXXX XXXX XXXXXX XXXXXX XXX
					XXXXXX
					XXXXX
						XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
					XXXXXX
				XXXXXX
                BBBBBB
                XXXX
				XXXXX
					XXXXX
						XXXXX
							XXXXXXXXX XXXXXXXX XXXXXXXXX
						XXXXXX
						XXXXX
							XXXXXXXXXXXXXXXXXXXX
							XXXXXXXXXX XX XXXXXXXXXXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXXX
						XXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXX
						XXXXXXXXXXX XXXX XXXXXX XXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
					XXXXXX
				XXXXXX
				XXXXX
					XXXXX
						XXXXX
							XXXXXXXXX XXXXXXXX XXXXXXXXX
						XXXXXX
						XXXXX
							XXXXXXXXXXXXXXXXXXXX
							XXXXXXXXXX XX XXXXXXXXXXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXXX XXXX XXXXXX XXXX XXXXXXXXXX
						XXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXX
						XXXXXXXXXXX XXXX XXXXXX XXXXXX
					XXXXXX
					XXXXX
						XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
					XXXXXX
				XXXXXX XXX
			XXXXXX
		XXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXX XXXXXX XX XXXX XXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
				XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
				XXXX XXXXXXXXXXXXXXXXXX XXX XXX XXXX X XXXXXXXX XXXX XXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXX XXX XXX XXXX X XXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            BBB B BB BBBBBBBBBBBBB
				XXXX XXXXXXXXXXXXXXXXXX
					XXXXX
						XXXXX
							
						XXXXXX
						XXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXX
							XXXXX FFFFFFFF FF FFF XXXXXX XXXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX
						XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXXX
					XXXXXX
				XXXXXX
            BBBBBB
            XXXX
				XXXX XXXXXXXXXXXXXXXXXXXXX
					XXXXX
						XXXXX
							XXXXXXXXX XXXXXXXX XXXXXXXXX
						XXXXXX
						XXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXXXXXX XX XXXXXXXXXXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX
						XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXXX
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXX
					XXXXX
						XXXXX
							XXXXXXXXX XXXXXXXX XXXXXXXXX
						XXXXXX
						XXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXXXXXX XX XXXXXXXXXXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX
						XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXXX
					XXXXXX
				XXXXXXXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXX
			XXXXXXXXXXXX XX XXXXXXX XXX XXXXXXXXXXXXXX
		XXXXXX
		XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXXXX
		XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXXXXXX XXXXXXX
	XXXXXX

  BBBB BBBBBBBBB
			BBBBBBB BBBBBBBBBBBBB
            BBBBBBB
XXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	XXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
		X
	XXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
		X
	XXX

	XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
        XXXXXXX X X XX X X XXXXXXXXX XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXX
            XX
        X
    XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXX
        XX
XXXXXXXXX
XXXXXXX